InfuseAI/piperider

piperider_cli/stage_runner.py
* Output the report URL to stdout when the test report is uploaded to piperider 
* Use the environment variable PIPERIDER_APP_URL to configure the test report URL. (Default: https://app.piperider.io)
Signed-off-by: Kent Huang <me@kent-huang.dev>
=> [Feature] sc-25564 Generate the report url when report is uploaded

piperider_cli/workspace.py
There is a compatible problem with `copytree`
```python
shutil.copytree(init_template_dir, working_dir, dirs_exist_ok=True)
```
=> Fix init errors at py 3.7

piperider_cli/workspace.py
dismiss SQLAlchemy warning of sqlite cannot support decimal objects natively
=> dismiss SQLAlchemy warning of sqlite

piperider_cli/cli.py
reproducible when there is no dbt profile.
```
root@2efe3ca2a8a8:/data#
root@2efe3ca2a8a8:/data# piperider-cli init
Usage: piperider-cli init [OPTIONS]
Try 'piperider-cli init --help' for help.
Error: Invalid value for '--dbt-profile-path': Path '/root/.dbt/profiles.yml' does not exist.
root@2efe3ca2a8a8:/data#
```
=> Fix init error without the dbt profile

piperider_cli/cli.py, piperider_cli/workspace.py
For no dbt enviornment
```
Usage: piperider-cli init [OPTIONS]
Try 'piperider-cli init --help' for help.
Error: Invalid value for '--dbt-profile-path': Path '/root/.dbt/profiles.yml' does not exist.
```
=> Fix dbt init prompt error if dbt profiles folder does not exist

tests/test_docs_existing.py
A simple checker for builtin assertion function.
```
E       Diff is 1117 characters long. Set self.maxDiff to None to see it.
tests/test_docs_existing.py:58: AssertionError
----------------------------- Captured stdout call -----------------------------
require docs for function [assert_row_count] at /home/runner/work/piperider-cli/piperider-cli/docs/assertions/assert_row_count.md
require docs for function [assert_column_type] at /home/runner/work/piperider-cli/piperider-cli/docs/assertions/assert_column_type.md
require docs for function [assert_column_in_types] at /home/runner/work/piperider-cli/piperider-cli/docs/assertions/assert_column_in_types.md
require docs for function [assert_column_min_in_range] at /home/runner/work/piperider-cli/piperider-cli/docs/assertions/assert_column_min_i …
```
=> Check docs for each builtin assertion functions

piperider_cli/cli.py
Before
```
piperider-cli init --help
Usage: piperider-cli init [OPTIONS]
Options:
--no-auto-search BOOLEAN  Don't search for dbt projects
--dbt-project-dir PATH    Directory of dbt project config
--dbt-profiles-dir PATH  Directory of dbt profiles config
--debug                  Enable debug mode
--help                   Show this message and exit.
```
After
```
piperider-cli init --help
Usage: piperider-cli init [OPTIONS]
Options:
--no-auto-search         Don't search for dbt projects
--dbt-project-dir PATH   Directory of dbt project config
--dbt-profiles-dir PATH  Directory of dbt profiles config
--debug                  Enable debug mode
--help                   Show this message and exit.
```
=> make no auto search as toggle

Dockerfile
check with `make docker-build`
```
=> [10/13] RUN apt-get update &&     apt-get install -y --no-install-recommends git     && apt-get purge -y --auto-remove     && rm -rf /var/lib/apt/lists/*               33.7s
=> [11/13] RUN pip install --no-cache-dir -r requirements.txt &&     pip install --no-cache-dir dbt-snowflake==1.1.0 snowflake-sqlalchemy==1.3.4 psycopg2-binary          151.5s
=> [12/13] WORKDIR /usr/src/github/                                                                                                                                         0.0s
=> [13/13] COPY entrypoint.sh /entrypoint.sh                                                                                                                                0.0s
=> exporting to image …
```
=> add packages for piperider-action image

piperider_cli/profiler/profiler.py, tests/profiler/test_profiler.py
Ref:
https://www.sqlite.org/datatype3.html
sqlite mismatched
column type | mismatched types
-------------------|-------------------------------
integer           | text, blob (set value to null)
numeric         | text, blob (set value to null)
text                 | no
datetime        | no
other              | no
Currently principle is make profiler works for non-numeric profiling metrics.)
=> Handle sqlite mismatched data

piperider_cli/workspace.py
fix unsupported operand type for dict
to support python before python 3.9
sc-26474
tested with `piperider run`, `piperider debug` with python 3.8
Node
=> fix unsupported operand type for dict before python3.9

piperider_cli/assertion_engine/__init__.py, piperider_cli/assertion_engine/assertion.py
- [v] Ensure you have added or ran the appropriate tests for your PR.
- [v] DCO signed
Bugfix
Fix 'bool' object is not iterable while asserting that does not required assert config.
sc-26568
=> Fix bool object is not iterable

piperider_cli/profiler/profiler.py
Bug
Current profiler transforms `sqlalchemy Date` and `Datetime` to python `datetime.date`.
It may call `date()` on a `date` object and cause an attribute error.
sc-26691
NONE
=> fix attribute error

piperider_cli/workspace.py
If there is no tests, the single and comparison reports would show empty page.
Bug fix
=> Make the `assertion_results` in output json are always non-null.

.github/workflows/nightly.yaml, piperider_cli/cli.py
- Manually trigger build will be `alpha` release
Fix Nightly build CI/CD
- Nightly build will remove `dev` in version
- Manually trigger nightly build will be `alpha` release
n/a
=> [Fix] nightly build version number without dev string

docs/user-defined-test-function.md, piperider_cli/data/piperider-init-template/plugins/customized_assertions.py
bugfix
the original sample, it would get logical errors:
```py
column_metrics = metrics.get('tables', {}).get(table, {}).get('columns', {}).get(column)
if not column_metrics:
pass
```
Because the `metrics` could be a `0` value, it was a `False` in the condition. Checking a `None` value is the only and correct way to know if a metric exists.
```py
column_metrics = metrics.get('tables', {}).get(table, {}).get('columns', {}).get(column)
if column_metrics is None:
pass
```
=> Update user-defined test functions sample

piperider_cli/assertion_engine/assertion.py, piperider_cli/error.py, piperider_cli/workspace.py
Bugfix
- Create `assertion` folder under `.piperider/` if this folder is not
existed
- Modify the error message if not profiling result found during command `generate-report` and `generate-assertions`
=> [Fix] sc-26965 Handle when not assertion folder found

piperider_cli/assertion_engine/recommended_rules/table_assertions.py
bug
it may recommend assertions in wrong format to a negative metric 
sc-27062
NONE
=> fix recommending range assertions in wrong format

piperider_cli/assertion_engine/assertion.py
bugfix
plugin-loader should also load modules when `diagnose` was called.
sc-27143
=> fix: plugin-loader should work either run or diagnose

static_report/src/components/ComparisonReport/ComparisonReport.tsx, static_report/src/components/SingleReport/SingleReport.tsx, static_report/src/utils/index.tsx
hotfix for not-shown `dbt_assertion_result`. will default to `-/-` when no assertions are provided
=> fix: typo on dbt assertion key (schema renaming)

static_report/src/components/ComparisonReport/CRList.tsx, static_report/src/components/ComparisonReport/CRModal/CRModal.tsx, static_report/src/components/ComparisonReport/CRModal/CRModalDbtTable.tsx, static_report/src/components/ComparisonReport/CRModal/CRModalPiperiderTable.tsx, static_report/src/components/ComparisonReport/CRTabProfilingDetails.tsx, static_report/src/components/ComparisonReport/CRTabSchemaDetails.tsx, static_report/src/components/ComparisonReport/CRTabTestDetails.tsx, static_report/src/components/ComparisonReport/CRTableColumnDetails.tsx, static_report/src/components/ComparisonReport/CRTableOverview.tsx, static_report/src/components/ComparisonReport/ComparisonReport.tsx, static_report/src/components/shared/GeneralTableColumn.tsx, static_report/src/components/shared/MetrisInfo.tsx, static_report/src/components/shared/NumericTableColumn.tsx, static_report/src/hooks/useComparisonChart.ts, static_report/src/sdlc/single-report-schema.d.ts, static_report/src/sdlc/single-report-schema.z.ts, static_report/src/types/index.ts, static_report/src/utils/assertion.ts, static_report/src/utils/formatters.tsx, static_report/src/utils/transformers.tsx
Update to UI layer. 
Change 'input' wording /codebase to 'target'; 
Additionally fixed any issues from uncaught property changes from schema (nullables)
SC 27377
Yes
Changed wording from 'input' to 'target', for generally recognizable vector of comparison data
=> Feature/sc 27377/compare reports rename all base input terms

piperider_cli/profiler/profiler.py
bug
The numeric metric, distribution, didn't show the max item on the latest bin.
sc-27602
NONE
=> fix: count of the last bin missing in distribution metric

.github/PULL_REQUEST_TITLE_CHECKER.json
Chore
Fix PR title checker prefixes end with a space
sc-27700
=> [Chore] sc-27700 Fix PR title checker prefixes end with a space

static_report/src/components/ComparisonReport/CRTabProfilingDetails.tsx, static_report/src/components/ComparisonReport/CRTableOverview.tsx, static_report/src/components/ComparisonReport/ComparisonReport.tsx, static_report/src/components/shared/ColumnCard/index.tsx, static_report/src/components/shared/GeneralTableColumn.tsx, static_report/src/utils/transformers.tsx
1. UI updates due to changes/deprecation of certain metrics (e.g. `mismatch`, `distribution`, `topk`, `histogram`)
2. Fix UI overflow of chart labels (`overflow-x` `clip` is used)
3. Fix UI use proper split chart vs. combined chart for Comparison Report charts (single vs. dual-bins)
27701, 27861, 27889
**Does this PR introduce a user-facing change?**: yes
1. Replaced `mismatch` references to `invalids`
2. Fix issue where Comparison Report charts was showing base/target histogram dual-bins when the charts should be split individually (single-bin)
3. Fix issue where report …
=> [Bug] comparison report changed metrics 27701

piperider_cli/__init__.py, piperider_cli/assertion_generator.py, piperider_cli/cli.py, piperider_cli/compare_report.py, piperider_cli/configuration.py, piperider_cli/filesystem.py, piperider_cli/generate_report.py, piperider_cli/runner.py
feature
Make the `report_dir` configurable, the `report_dir` is the parent path of `outputs` and `comparisons`
By default, they are located at `.piperider`.
sc-27845
In this PR, we also remove the variables and introduce `FileSystem` object to handle the directory configurable:
* PIPERIDER_OUTPUT_PATH
* PIPERIDER_COMPARISON_PATH
* PIPERIDER_REPORT_PATH (never used)
```yaml
dataSources:
- name: demo
type: sqlite
report_dir: ./foo/bar
```
Users could configure the `report_dir` in their `config.yml`. The `.` relative directory always refer to `.piperider` itself.
For example:
* `.` will be `$CWD/.piperider` (default behavior)
* …
=> [Feature] Support to change the report directory by --report-dir

piperider_cli/datasource/snowflake.py
chore
timeout setting is too strict for large dataset query
sc-27838
https://docs.snowflake.com/en/user-guide/odbc-parameters.html#optional-connection-parameters
`login_timeout`: Default is 60 (seconds).
`network_timeout`: Default is no timeout setting.
NONE
=> [Chore] Revert snowflake odbc default timeout value

piperider_cli/datasource/bigquery.py
Bugfix
Fix gcloud command can not execute by copy past
sc-28110
=> [Bug] sc-28110 fix gcloud command can not execute by copy past

static_report/package.json, static_report/src/components/ComparisonReport/CRTableList/CRTableListColumnList.tsx, static_report/src/components/SingleReport/SRTableList/SRTableListColumnList.tsx, static_report/src/utils/formatters.tsx, static_report/yarn.lock
**Columns**
**Generated time with timezone**
- When assertions equal to 0, still need to display information of columns
- Enhancement of the report generated time with user's current timezone
=> [Bug] iterate table.columns instead of assertions to display columns

piperider_cli/assertion_engine/assertion.py
Bug
Custom assertion cannot be assigned a falsy 'actual' field, 
then causes `IllegalStateAssertionError('Assertion Function should fill 'actual' and 'expected' fields.')`
sc-28398
NONE
=> [Bug] Fix custom assertion exception when falsy actual field given

static_report/src/components/SingleReport/SingleReport.tsx
- added default values to assertions because if one of values is `undefined`, the statement (`undefined === 0`) will equal to `false`
=> [Bug] add default values to assertions check

static_report/src/App.tsx, static_report/src/components/shared/BreadcrumbNav.tsx, static_report/src/components/shared/Tables/TableActionBar.tsx, static_report/src/components/shared/Tables/TableList/CRTableListItem/CRTableListAssertions.tsx, static_report/src/pages/CRColumnDetailsPage.tsx, static_report/src/pages/CRTableDetailsPage.tsx, static_report/src/pages/CRTablesListPage.tsx, static_report/src/pages/SRColumnDetailsPage.tsx, static_report/src/pages/SRTableDetailsPage.tsx, static_report/src/pages/SRTablesListPage.tsx, static_report/src/utils/assertion.ts, static_report/src/utils/layout.ts, static_report/src/utils/routes.ts
Feature
Add a simple global breadcrumb for page-level usage (also for library UI)
https://www.loom.com/share/37aea0ac81ba4ea9870d68662b2165b2
The breadcrumb logic is very simple. But I think will serve our usage fairly easily (when routing gets more complex in cloud, we can revisit the logic)
```
* A breadcrumb UI that will use browser location to render breadcrumbs based on the route-params manually provided.
* FULL_URL1: `/tables/ACTION`
* BREADCRUMB: `['/', '/tables/ACTION']
*
* FULL_URL2: `/tables/ACTION/columns/FOO`
* BREADCRUMB: `['/', '/tables/ACTION', …
```
=> [Feature] simple breadcrumb nav 2

docs/config.md, piperider_cli/configuration.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, tests/profiler/test_profiler.py
Feature
to enhance the profiling of large datasets with a limited number of rows for quick navigation.
#400
sc-28353
In the `.piperider/config.yml`, add this configuration.
```
profiler:
table:
limit: 1000000
```
NONE
=> [Feature] Add table profiling rows limit

piperider_cli/profiler/profiler.py, tests/profiler/test_profiler.py
bug
overflow may happen during calculating `stddev`
sc-28645
And we use built-in `sample stddev` for data sources other than sqlite.
NONE
=> [Bug] Use built-in stddev in all data sources except sqlite

piperider_cli/error.py
change this message in the CLI:
`Please run 'pip install piperider[csv]' to get the csv connector`
to
`Please run "pip install 'piperider[csv]'" to get the csv connector`
The original one does not work in zsh
=> [Bug] Fix the quotation of pip install message

piperider_cli/profiler/profiler.py
bug
bigquery treated SELECT list alias as table name and threw out "cannot `GROUP BY` field references from SELECT list alias"
sc-28939
NONE
=> [Bug] Add column alias for duplicate row query

piperider_cli/configuration.py, piperider_cli/event/__init__.py
If the user remove the telemetry id from the `config.yml`, we will not collect the telemetry event.
sc-28960
=> [Bug] Don't collect telemetry event if telemetry id is removed

piperider_cli/profiler/profiler.py
feature
To keep columns profile results entries in order when multi-thread profiling
sc-28850
NONE
=> [Feature] Preallocate column profiling result entries

piperider_cli/profiler/schema.json, static_report/src/components/shared/Tables/TableMetrics/DupedTableRowStats.tsx, static_report/src/components/shared/Tables/TableMetrics/TableGeneralStats.tsx, static_report/src/components/shared/Tables/TableOverview.tsx, static_report/src/components/shared/Widgets/DupedTableRowsWidget.tsx, static_report/src/components/shared/Widgets/QuantilesWidget.tsx, static_report/src/pages/CRColumnDetailsPage.tsx, static_report/src/sdlc/single-report-schema.ts
fix
- Minor UI issues: squished comparison table-overview info (duplicate rows, table composition);
- quantile's extra padding misaligned with layout
- fix schema title (breaks typescript json schema generator)
none
**Does this PR introduce a user-facing change?**: yes
- On certain screen sizes, the squished comparison table-overview info is fixed (duplicate rows, table composition);
- Quantile's extra padding misaligned with layout is fixed
=> [Bug] - squished table details page; schema legacy_assertIon_test `title` property

docs/assertions-builtin.md, docs/assertions-custom.md, piperider_cli/assertion_engine/assertion.py, piperider_cli/assertion_engine/event.py, piperider_cli/assertion_engine/recommended_rules/table_assertions.py, piperider_cli/assertion_engine/types/__init__.py, piperider_cli/assertion_engine/types/assert_column_misc.py, piperider_cli/assertion_engine/types/assert_column_ranges.py, piperider_cli/assertion_engine/types/assert_column_types.py, piperider_cli/assertion_engine/types/assert_metrics.py, piperider_cli/assertion_engine/types/assert_rows.py, piperider_cli/assertion_engine/types/base.py, piperider_cli/assertion_generator.py, piperider_cli/data/piperider-init-template/plugins/customized_assertions.py.template, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, tests/_user_defined_assertion_functions.py, tests/test_builtin_assertions.py, tests/test_user_defined_assertions.py
feature
support more column value check
sc-29028
The interface of the assertion class is changed.
The `execute` only accepts one assertion context as the input parameter.
- original `customized_assertions.py.template`
```python
class AssertNothingTableExample(BaseAssertionType):    
def execute(self, context: AssertionContext, table: str, column: str, metrics: dict) -> AssertionResult:
```
- new `customized_assertions.py.template`
```python …
```
=> [Feature] Add column value in set assertion

piperider_cli/assertion_engine/assertion.py, piperider_cli/profiler/schema.json
feature
only allow one name or one metric property in assert test entry
sc-29029
NONE
=> [Feature] Allow only name or only metric in assert test entry

piperider_cli/configuration.py
feature
dbt's official `profiles.yml` loading behavior has been changed.
The PR is to make PipeRider align with the same behavior.
sc-29425
Precedence reference:
https://docs.getdbt.com/docs/get-started/connection-profiles#advanced-customizing-a-profile-directory
NONE
=> [Feature] Change dbt profiles yaml load behavior

piperider_cli/runner.py
The option --dbt-state should not profile the views
bug
- tables we retrieved from `dbt-state` is a table filter
NONE
=> [Bug] The option --dbt-state should not profile the views

piperider_cli/configuration.py
bug
- dbt can load `dbt_project.yml` and `profiles.yml` with duplicated keys.
- align piperider behavior when loading `dbt_project.yml` and `profiles.yml`.
sc-29650
NONE
=> [Bug] Allow piperider load duplicated key in dbt yaml

static_report/src/components/Tables/TableActionBar.tsx
*Before*
*After*
I checked the OSS currently didn't use `children` anymore and we can move `children` out of the source name block.
- adjustment table action bar children prop position
=> [Chore] adjustment TableActionBar children prop position

piperider_cli/profiler/profiler.py
Fix #533 
Bug
If max value of datetime column is huge, it would bump into python datetime overflow. (max=9999-12-31) 
#533
sc-29904
Set the upper bound for datetime histogram to prevent for running into exception
=> [Bug] Fix the datetime overflow problem while profiling

piperider_cli/datasource/__init__.py, piperider_cli/datasource/field.py, piperider_cli/datasource/snowflake.py
Add two more configuration
SSO: https://docs.snowflake.com/en/user-guide/admin-security-fed-auth.html
Key pair: https://docs.snowflake.com/en/user-guide/key-pair-auth.html
Key/pair
```
private_key_path: <path to the private key>
private_key_passphrase: <keyphase for the private key>
```
SSO. see [link](https://docs.snowflake.com/en/user-guide/python-connector-api.html#functions)
```
authenticator: 'externalbrowser' or 'https://<okta_account_name>.okta.com'
```
Feature
#532 
sc-29948
Yes
=> [Feature] Support keypair and SSO authentication in snowflake connector

static_report/src/components/Columns/MasterSideNav/ColumnListAccordionPanel.tsx, static_report/src/components/Columns/MasterSideNav/MasterSideNav.tsx
Fix
Fix bug in sidenav report menu (refreshing page doesn't expand the correct active nested item)
N/A
**Does this PR introduce a user-facing change?**: Yes
Now on page refresh of a actively selected table or column, the sidebar initially show active item as expanded
=> [Bug] : broken initial load of toggled index for selected table/column (data-sidebar)

piperider_cli/configuration.py
bug
- in dbt postgres project, credential entry name `pass` and `password` is allowed.
NONE
=> [Bug] Fix compatibility of dbt profile entry name

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py
- Auto upload will default disable
- Ask user to select defatul project if there are multiple projects
Feature
- Ask user to select default project when login or signup if there are more than one project in the cloud.
- Default disable auto-upload flag when user first time sign up or login
sc-30606
=> [Feature] sc-30606 Select project when signup or login

static_report/src/App.tsx
Feature added
PipeRider hasn't supported showing reports on mobile devices. We only show the warning message when found a browser with a mobile device user-agent name.
sc-30597
----
https://piperider-dev-tmp.s3.ap-northeast-1.amazonaws.com/sc30597/git_repo_analytics-20230301160820/index.html
=> [Feature] warning users are reading report in non-supported mobile device

piperider_cli/hack/inquirer.py
- bug
- When piperider depends on inquirer v3.1.3, the `LimitedCheckboxQuestion` has a missing attribute.
sc-30803
NONE
=> [Bug] Fix compatibility of inquirer v3.1.3

piperider_cli/cloud_connector.py
The response of **upload report** and **make compare report ** contains the `url` for the report. The PR is to use the `url` to print the report url.
=> [Feature] The CLI use the server response to get the report url

piperider_cli/datasource/bigquery.py, piperider_cli/profiler/profiler.py, setup.py
Because `pybigquery` is obsolete. Change to use the new `python-bigquery-sqlalchemy'
Feature
For old python environment, user needs to install the latest sqlalchemy engine. `piperider install 'piprider[bigquery]'`
=> [Feature] The sqlalchemy bigquery connector changes to use python-bigquery-sqlalchemy'

piperider_cli/runner.py
Fix #626
To set `PIPERIDER_SKIP_TARGET_CHECK=1`  to skip the target check.
Example:
```
$ export PIPERIDER_SKIP_TARGET_CHECK=1
$ piperider run
```
Feature
See #626 
#626, sc-30840
=> [Feature] Allows to skip the target check

piperider_cli/generate_report.py
feature
- output absolute report path
sc-30549
both `os.path.islink` and `os.path.realpath` can work in a non admin Windows enviornment
NONE
=> [Feature] Output absolute report path when piperider run

Makefile, piperider_cli/cloud_connector.py
bug
- if the uploaded report URL's length is too long, the URL would be cropped.
sc-31109
when the URL is folded, the link cannot be clicked directly.
NONE
=> [Bug] Fold uploaded report url when it's larger than available space

README.md, piperider_cli/cli.py, piperider_cli/configuration.py
- To profile no model by default
- Add one step in README for applying tags
- Add hint for applying tags after initialized
Feature
Change to profile no model by default for dbt project
**Screenshots**
Added a hint after `piperider init`
=> [Feature] Enable piperider tag by default for dbt project

piperider_cli/cli.py
bugfix
make recipe executor to upload reports to a specific cloud project.
sc-31124
=> [Bug] Fix unset project-name in recipe execution

README.md, piperider_cli/assertion_generator.py, piperider_cli/cli.py, piperider_cli/initializer.py, static_report/src/components/Columns/MasterSideNav/MasterSideNav.tsx, static_report/src/components/Common/HelpMenu.tsx, static_report/src/components/Common/Navbar.tsx, static_report/src/pages/CRAssertionListPage.tsx, static_report/src/pages/SRAssertionListPage.tsx
Feature
- Mark assertions and non-dbt project as deprecated
- Report will not show assertions if there are no assertions data
- Report will show assertion is deprecated when showing the assertions result
- Update README.md
sc-31205
=> [Feature] sc-31205 Mark assertions page as deprecated in front-end page

piperider_cli/cli.py, piperider_cli/dbtutil.py, piperider_cli/runner.py, tests/test_dbt_util.py, tests/test_runner.py
Feature
- When running command with `--table` option, piperider will only show the dbt test results with the selected table
- Default enable the flag `dbt-run-results` if the `run_results.json` is found. Disable this flag if there is no `run_results.json` file.
sc-31437
=> [Feature] sc-31437 Default enable dbt-run-results flag if file exists

piperider_cli/dbtutil.py
Bugfix
- Check depends_on.nodes
- Skip the metric if calculation_method != dervied and depends_on.nodes is empty.
sc-31348
=> [Bug] Skip the metric if depends_on.nodes is empty

piperider_cli/compare_report.py
bug
- piperider raised keyerror when compare-reports with `--tables-from` option
sc-31507
NONE
=> [Bug] Fix keyerror of compare-reports with --tables-from option

piperider_cli/runner.py
For dbt project, use `--table` would not profile all models, but it show the dbt tree. The items we click would not show report correctly
=> [Bug] The report would encounter error if use --table option

piperider_cli/runner.py
If there is no `target-path`, piperider cannot run successfully
=> [Bug] cannot run piperider if the dbt project has no target-path settings

piperider_cli/runner.py
Dont contain `run_results` key at `dbt` of `run.json` if dbt run results does not exist
=> [Chore] Dont contain run_results key if dbt run results does not exist

piperider_cli/runner.py
Bugfix
For source node, `name` field might not be the actual table name, but `identifier` does.
Read the `identifier` field instead of `name` one.
=> [Bug] Fix wrong source table name when users specify identifier in dbt schema

piperider_cli/dbtutil.py
It's only happens while developing:
1. copy other manifest.json to my project
2. run piperider
3. the `run_results` cannot find corresponding id in the manifest.
=> [Bug] If the run result and manifest does not match, it would cause error.

piperider_cli/dbt/list_task.py, piperider_cli/reports/__init__.py
bug
- change comparing manifest direction
- append empty `{}` when no corresponding column
sc-31660
NONE
=> [Bug] Exchange manifest direction and append empty dict

piperider_cli/cli.py, piperider_cli/dbt/list_task.py, piperider_cli/dbtutil.py, piperider_cli/error.py, piperider_cli/recipe_executor.py, piperider_cli/recipes/default_recipe_generator.py, piperider_cli/runner.py
Feature
- PipeRider `run` command support options `-s` or `--select` The logic will be equaled as dbt's `--select` option.
- Piperider `compare` command support options `-s` or `--select`. But it will only be affected when no default recipe is found. If the user has provided a recipe file, we will execute the `--select` option and ignore the recipe file.
SC-31590
No
=> [Feature] sc-31590 Run command support -s to select dbt models

piperider_cli/recipe_executor.py
Bugfix
Fix piperider compare command throw error "'int' object has no attribute 'dump'"
sc-31751
=> [Bug] sc-31751 Fix compare command throw error  'int' object has no attribute 'dump'

piperider_cli/dbt/list_task.py, tests/mock_dbt_data/sc-31587-metrics-base.json, tests/mock_dbt_data/sc-31587-metrics-input.json, tests/test_dbt_integeration.py
enhancement
improve unique-id resolving compatibility for report data
None
For the newer report, we put `ref_id` to each resource entry to make unque-id resolving easy. However, the user might compare any two reports in these cases:
1. both without ref_id
2. base wit ref_id, input without ref_id
3. base without ref_id, input with ref_id
4. both with ref_id
This PR support all resolving cases
=> [Chore] Update unique-id resolving strategy

piperider_cli/dbtutil.py
Chore
From dbt 1.5.x, `dbt list` will output runtime logs as well
dbt 1.5.2:
```
$ dbt list -s raw_payments
08:57:55  Running with dbt=1.5.2
08:57:55  Registered adapter: duckdb=1.5.2
08:57:55  Found 6 models, 20 tests, 0 snapshots, 0 analyses, 316 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 1 metric, 0 groups
jaffle_shop.raw_payments
```
dbt 1.4.6:
```
$ dbt list -s raw_payments
jaffle_shop.raw_payments
```
Actually, the runtime logs won't affect the process but it's better to ignore them from reading
=> [Chore] Ignore dbt runtime logs when reading stdin from dbt list command

static_report/src/pages/CRTableDetailPage.tsx, static_report/src/pages/SRTableDetailPage.tsx, static_report/src/utils/dbt.ts
If the model is materialized as 'external' or 'ephemeral', there would be no actual table/view in the data warehouse. We should show the report without error in this case.
=> [Bug] Handle the case that the model has no piperider profiling information

piperider_cli/dbt/list_task.py
- Config cv_project_root when dbt-core is larger than 1.5.2
Bugfix
- Since dbt-core v1.5.2, we need to configure `cv_project_root` during Task.
sc-31578
=> [Bug] sc-31578 Fix lookup error when use select option

piperider_cli/cli.py
Bugfix
- We refine the compare recipe flow, the base phase will be excuted first. Don't need to set `reverse_last` flag anymore.
sc-31833
=> [Bug] sc-31833 Remove reverse_last flag when execute compare command

piperider_cli/recipes/github_action.py
Feature
- For GitHub Compare Action, support to add new option `--base-branch` when generate the compare commands
- Don't check git branch if there is no recipe specified by GtiHub Action
sc-31777
=> [Feature] sc-31777 Add base_branch option when trigger by github action

piperider_cli/dbtutil.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/utils.py
Bugfix
- Execute `dbt compile` at the current working directory if there is no `target/manifest.json` file found before listing dbt resources
sc-31865
=> [Bug] sc-31865 Handle edge case if no manifest.json found when compare

piperider_cli/recipe_executor.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/default_recipe_generator.py
Feature
- Target phase will run dbt build with `--select state:modified+ --state <state_path>` when Piperider compare command with `--modified` options or `--select` contain `state:modified` insided.
sc-31829
=> [Feature] sc-31829 Use dbt build with state modified when using modified

piperider_cli/dbt/utils.py, tests/test_compare_summary_ng.py
> ## TypeError
> '>' not supported between instances of 'NoneType' and 'float'
Get report from sentry
=> [Bug] Fix compare with NoneType

piperider_cli/recipes/github_action.py
BugFix
Force to run git switch in GitHub Action even if there is no recipe file.
sc-31930
=> [Bug] sc-31930 Force GitHub Action to switch branch even no recipe

static_report/src/utils/routes.ts
it will render too much time when switching between column. The root cause is we use too much `useRoute`, it will make the render several times when changing the path.
=> [Bug] Improve column switching performance

.github/workflows/e2e-windows-tests.yaml, e2e-jaffle-shop/run.bat, e2e-jaffle-shop/windows-result-checker.py, piperider_cli/cloud_connector.py, piperider_cli/compare_report.py, piperider_cli/configuration.py, piperider_cli/datasource/duckdb.py, piperider_cli/generate_report.py, piperider_cli/recipes/utils.py, piperider_cli/runner.py, piperider_cli/utils.py, tests/test_links.py
bugfix
A Windows user can run piperider without the administrator role.
sc-31866
----
- for legacy duckdb implementation, it is poor to support `multi-` read and write, we treat it in a different way: only create an `sqlalchemy-engine` for it.
- Add `jaffle_shop` e2e tests for windows, only 1 combination (the latest dbt and python)
=> [Bug] Make piperider working on windows

piperider_cli/cloud/__init__.py, piperider_cli/dbt/changeset.py, piperider_cli/dbt/utils.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, tests/profiler/test_multi_db.py
bugfix
In a real case, users might use the same name for different dbt nodes. 
For example:
* define `transaction` in the sources
* define `transaction` in the seed
* define `transaction` in the model
* ~~define `transaction` in the staging model~~
> (venv) (⎈ |kind-kind:default)(base) ➜  tw_campaign_finance git:(chore/rename) ✗ dbt build
> 03:17:51  Running with dbt=1.5.2
> 03:17:51  Registered adapter: duckdb=1.5.2
> 03:17:51  Encountered an error:
> Compilation Error
>   dbt found two models with the name "transaction".
> 
>   Since these resources have the same name, dbt will be unable to find the correct resource
>   when looking for ref("transaction").
> 
>   To fix this, change the name of one of …
=> [Bug] Handle naming conflict problem in profiler and report-generator

.github/workflows/dbt-compatible-tests.yaml
Got a problem with the dbt 1.4 latest release, skip it for now. I will check it later.
---
* broken tests: https://github.com/InfuseAI/piperider/actions/runs/5783283543/job/15671764017
* diff between 1.4.6 and 1.4.7 https://github.com/dbt-labs/dbt-core/compare/v1.4.6...v1.4.7
=> [Chore] Skip dbt-1.4.7 for regression error

piperider_cli/datasource/duckdb.py, piperider_cli/dbtutil.py, tests/test_cli.py
Unit Test
- Add unit test for CLi to test `init`, `diagnose` and `run` commands
- Fix some path related issues
- Currently, duckDB will only search the db file from CWD. After this fix, we will search CWD first and search working_dir secondly. 
- When we use `--dbt-project-dir` to config dbt project dir, the method `load_dbt_project` will use a wrong path to load file.
N/A
=> [Chore] refactor test-cli.py to test init, diagnose and run commands

static_report/cypress/e2e/comparison-report.cy.ts, static_report/src/components/Common/Main.tsx, static_report/src/components/Common/MasterDetailContainer.tsx, static_report/src/components/Reports/ReportContextBar.tsx, static_report/src/types/index.ts, static_report/src/utils/store.ts
Show PR id/title/link in the comparison report.
**OSS** 
**Cloud** 
=> [Feature] backlinks to pr in comparison reports UI

static_report/src/utils/dbt.ts
=> [Bug] Don't show change icon if one side is not profiled

piperider_cli/cloud_connector.py, piperider_cli/compare_report.py, piperider_cli/dbt/changeset.py, static_report/src/components/LineageGraph/CopyGraphUrlButton.tsx
Add the cloud report with `utm_source` information
1. CLI: utm_source=cli
2. PR Comment: utm_source=pr
3. Copy button: utm_source=share
4. Lineage diff: utm_source=lineage 
=> [Chore] Add utm_source in the cloud report

piperider_cli/profiler/profiler.py
If there is a very large date, it will hit the overflow exception
```
Error: Profiler Exception: OverflowError('date value out of range')
```
Example sql
```
SELECT '9999-12-31 00:00:00 +0000'::timestamp_tz as d
```
=> [Bug] Fix the overflow issue if the datetime column has very large date

piperider_cli/dbt/list_task.py
Bug
* fix dbt-1.3 broken by flags function
* add the new flag introduced from dbt-1.6.1
=> [Bug] fix compatible problem for dbt-1.3  and dbt-1.6.1

piperider_cli/configuration.py
Bugfix
Fix NoneType error when piperider config file is empty
sc-32142
=> [Bug] sc-32142 Throw NoneType error when piperider config file is empty

static_report/src/components/Overview/Overview.tsx, static_report/src/types/index.ts
bugfix
show **impact summary** broken messages
sc-32180
This PR only updates the UI, it must be working with the API server.
=> [Bug] add warning at impact summary

piperider_cli/compare_report.py, piperider_cli/runner.py
Enhance
- Replace manifest `raw_code` field by sha1 hash to reduce the file size of `run.json` if the manifest size is larger than 10MB
- Show report size when selecting the upload reports
sc-32147
=> [Chore] sc-32147 Reduce the file size of `run.json` to speed up the report upload time

static_report/schema/dbt-manifest-schema.json, static_report/src/components/Icons/index.tsx, static_report/src/components/LineageGraph/GraphNode.tsx, static_report/src/components/LineageGraph/util.ts, static_report/src/pages/CRPage.tsx, static_report/src/pages/CRSemanticModelPage.tsx, static_report/src/pages/SRPage.tsx, static_report/src/pages/SRSemanticModelPage.tsx, static_report/src/sdlc/dbt-manifest-schema.ts, static_report/src/types/index.ts, static_report/src/utils/dbt.ts, static_report/src/utils/routes.ts
Should handle the `semantic_models` in the lineage diff
Bug
sc-32214
=> [Bug] Add semantic models to lineage graph

piperider_cli/dbtutil.py, piperider_cli/metrics_engine/metrics.py
feature
- We have supported basic dbt 1.6 metric query but have some limitations.
sc-32064
NONE
=> [Feature] Add restriction to dbt 1.6 metric support

piperider_cli/dbt/changeset.py
comparison generating failed when impacted models are more than 50. It's because the footer column count of the markdown is not the same as the header row count
Bug fix
=> [Bug] comparison generating failed when impacted models are more than 50

piperider_cli/__init__.py, piperider_cli/event/__init__.py
Chore
- If user's home directory is read-only, needs to find a place to store `.piperider/profile.yml` 
sc-32247
=> [Chore] sc-32247 Fallback to use temp folder to store profile.yml

piperider_cli/cli.py, piperider_cli/recipe_executor.py, piperider_cli/recipes/default_recipe_generator.py, piperider_cli/recipes/utils.py
feature
- When `piperider compare` is executed, piperider automatically generates a recipe for users.
- We need a better way to give users a hint to specify the base branch and deal with the branch not found problem.
sc-32156
#866 
NONE
=> [Feature] Improve base branch selection in compare

piperider_cli/dbt/list_task.py
Chore
- Fix unit test failed issues by dbt-core v1.6.2
N/A
=> [Chore] Fix unit-test failed by dbt-core 1.6.2

piperider_cli/cloud_connector.py, piperider_cli/compare_report.py, piperider_cli/githubutil.py
Feature
- Read GitHub PR info from `GITHUB_PR_ID`, `GITHUB_PR_URL` and `GITHUB_PR_TITLE`
sc-32261
=> [Feature] sc-32261 Read GitHub PR info from env var

piperider_cli/cli.py, piperider_cli/cli_utils/compare_with_recipe.py, piperider_cli/dbt/list_task.py, piperider_cli/dbtutil.py, piperider_cli/recipe_executor.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/default_recipe_generator.py, piperider_cli/recipes/github_action.py, piperider_cli/recipes/utils.py, piperider_cli/runner.py, tests/test_recipe.py
feature
- to support `piperider compare <git-ref>...<git_ref>`
sc-31643
NONE
=> [Feature] Support piperider compare between git refs

piperider_cli/cli.py, piperider_cli/cli_utils/__init__.py, piperider_cli/cli_utils/compare_with_recipe.py, piperider_cli/cli_utils/run_cmd.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/compare_report.py, tests/test_cli.py
Feature
- Enable Quick Look upload by feature flag `--enable-quick-look-share` or ENVVAR `PIPERIDER_ENABLE_QUICK_LOOK_SHARE=true`
- Use option `--share` without login PipeRider Cloud, upload the report to PipeRider Temporary Quick Look
- Support commands:
- `run`
- `compare-reports`
- `compare`
| Is Login | `--upload` | `--share` | `--enable-quick-look-share` | Upload Behavior |
|----------|------------|-----------|-----------------------------|-----------------|
| ✅ | ❌ | ❌ | ❌ or ✅| Do nothing |
| ✅ | ✅ | ✅ | ❌ or ✅| Upload & Share to project| 
| ✅ | ❌ | ✅ | ❌ or ✅| Upload & Share to project| 
| ✅ | ✅ | ❌ | ❌ or ✅| Upload to project| 
| ❌ | ❌ | ❌ | ❌ or ✅ | Do nothing |
| ❌ | ✅ | ❌ | ❌ or ✅ | Do …
=> [Feature] sc-32292 PipeRider CLI support share to temporary quick look

piperider_cli/dbt/list_task.py, tests/test_dbt_integeration.py
bugfix
add the required `dbt_cloud` arg
sc-32397
It can not be checked by the version of dbt-core, we should ask the specific field in the dataclass
=> [Bug] Fix dbt-core breaking our task runner

piperider_cli/profiler/profiler.py
bugfix
We can not help in this case, the remote report is useless.
sc-32373
=> [Bug] stop sending report when no-such-table

piperider_cli/datasource/bigquery.py, piperider_cli/datasource/bigquery_patch.py
feature added
add GCP service-account impersonation support
sc-32423
* We use monkey-patch to wrap credentials to impersonated credentials
* The implementation is temporary until https://github.com/googleapis/python-bigquery-sqlalchemy/pull/906/files add official support
----
Piperider will use `impersonate_service_account` to profile data
```yaml
jaffle_shop_bq:
outputs:
dev:
dataset: my_dataset
job_execution_timeout_seconds: 300
job_retries: 1
location: US
method: service-account
priority: interactive
project: dev
threads: 1
type: bigquery
keyfile: service-account.json
impersonate_service_account: …
```
=> [Feature] Support impersonate service-account for BigQuery

piperider_cli/event/__init__.py
bug
- profiler would load user profile when an exception happens, and we need to make `load_user_profile` thread safe.
sc-32407
NONE
=> [Bug] Failed to read yaml file in concurrent

piperider_cli/event/collector.py
bug
- add a handler when loading a broken json file
sc-32380
NONE
=> [Bug] Add a handler to unexpected json file format

piperider_cli/recipes/__init__.py
bug
- compare with a recipe will provide dbt resources for further profiling.
- it should not affect the profiler when user defines their own recipe.
sc-32418
NONE
=> [Bug] Skip passing dbt resources when compare with custom recipe

piperider_cli/cli.py, piperider_cli/cli_utils/run_cmd.py, piperider_cli/cloud/__init__.py, piperider_cli/configuration.py, piperider_cli/initializer.py, piperider_cli/runner.py, piperider_cli/validator.py
Feature request from GitHub issue #898 
- Add options `--dbt-profile` and `--dbt-target` for `init`, `diagnose` and `run commands
- Users can specific the DBT profile or target when executing the `run` command.
sc-32422
#898 
=> [Feature] sc-32422 Add option to select dbt profile and target

Dockerfile
chore
- update outdated piperider version in the dockerfile
sc-32404
NONE
=> [Chore] Update piperider version in dockerfile

piperider_cli/validator.py
bug
- in a legacy Windows console, some Unicode emojis would cause the unicode encoding error.
sc-32406
NONE
=> [Bug] Escape unsupported unicode emojis for legacy windows console

piperider_cli/recipes/__init__.py
Bugfix
- If the dbt config is configured under the data source field. Handle this edge case.
```yaml
dataSources:
- name: infusetude_dev
type: snowflake
dbt:
profile: infusetude
target: dev
projectDir: .
profilesDir: .
- name: infusetude
type: snowflake
dbt:
profile: infusetude
target: prod
projectDir: .
profilesDir: .
...
```
sc-32474
=> [Bug] sc-32474 Fix compare error if no global dbt config

piperider_cli/__init__.py, piperider_cli/assertion_engine/assertion.py, piperider_cli/assertion_engine/recommender.py, piperider_cli/cloud/__init__.py, piperider_cli/configuration.py, piperider_cli/dbtutil.py, piperider_cli/event/__init__.py, piperider_cli/initializer.py, piperider_cli/recipes/__init__.py, piperider_cli/yaml/__init__.py, tests/test_builtin_validations.py, tests/test_builtin_validations_column_types.py
chore
The latest yaml library will break our code, we must make it compatible.
sc-32483
=> [Chore] introduce Anti-corruption Layer for yaml library

piperider_cli/cloud/__init__.py
bug
- add error handler when a response can not be decoded in json format.
sc-32458
NONE
=> [Bug] Add handler for server side error response when uploading report

static_report/src/components/Reports/ReportContextBar.tsx, static_report/src/sdlc/single-report-schema.ts
bug
- after `v0.34.0`, `git_branch` information in a run report could be null when compared with git references other than branches.
sc-32458
NONE
=> [Bug] Update static report schema

piperider_cli/datasource/duckdb.py
feature
- feed s3 configuration to duckdb engine
sc-32497
NONE
=> [Feature] Connect to S3 with AWS access key and secret for duckdb

piperider_cli/error.py
bugfix
Convert message from any kinds of exceptions
sc-32507
=> [Bug] Fix no attributes error

piperider_cli/compare_report.py
chore
- the `compare-reports` command filtered reports from different targets before, right now we would like to remove this limitation due to more emphasis on the base-target comparison.
sc-32530
NONE
=> [Chore] Adjust compare-reports command behavior

.github/workflows/tox.yaml, piperider_cli/yaml/__init__.py, setup.py, tox-ruamel.ini, tox-sqlalchemy.ini
bugfix
* Make the yaml parser more compatible with legacy versions
sc-32539
We also re-arrange the test matrix by tox.
=> [Bug] Make the ruamel integeration compatiable with legacy versions

piperider_cli/configuration.py
bug
- fix how piperider decides dbt default target
sc-32560
NONE
=> [Bug] Fix default dbt target decision policy

piperider_cli/dbtutil.py
Bugfix
- When the user uses `run` command with option `--dbt-list`, the list is piped from stdin. (Ex. `dbt list -s 'tag:piperider' | pieprider run --dbt-list` ). The dbt-list function doesn't work.
- Before, we only compared the node's `unique_id` with select dbt resources. However, the format of `uniqueId` could not be matched with dbt_resource.
Ex. `node['uniuqe_id']` is `model.jaffle_shop.stg_customer`, `dbt_resources['models']` is `jaffle_shop.staging.stg_customers`
- In this fix, we will not only compare the `unique_id`. But also compare the dbt_resources with FQN.
[PR-55](https://linear.app/piperider/issue/PR-55/piperider-run-options-dbt-list-doesnt-work) …
=> [Bug] PR-55 Fix option `--dbt-list` doesn't work issue
