piperider_cli/stage_runner.py
```
$ piperider-cli run --stage piperider/stages
```
```
$  tree
.
├── data.csv
├── local_input_c59c2bdb213b5f9e335d32dae79e3ecb.json
├── local_input_c59c2bdb213b5f9e335d32dae79e3ecb_ydata.json
├── piperider
│   ├── data.csv
│   ├── harness
│   ├── sources
│   │   ├── local.yaml
│   │   └── snowflake.yaml
│   ├── stages
│   │   ├── local.yaml
│   │   └── snowflake.yaml
│   └── tests
├── snowflake_input_68826d1fc4627a6685f0291acd9c54bb.json
└── snowflake_input_68826d1fc4627a6685f0291acd9c54bb_ydata.json
```
`*_ydata.json` are ydata reports
=> Generate ydata json report

piperider_cli/stage_runner.py, piperider_cli/ydata/data_expectations/engine.py
Exit with code (1) if any warnings
=> Return exit code 1 if any warnings

piperider_cli/cli.py, piperider_cli/custom_assertion.py, piperider_cli/data/convert_to_exp.py, piperider_cli/data/examples/functions.py, piperider_cli/data/examples/stage_custom_assertions.yml, piperider_cli/great_expectations/expect_column_values_pass_with_assertion.py, piperider_cli/workspace.py, setup.py
Basic idea:
* add a stub expectation for callback from PipeRider's custom asserts
Ref:
* https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_map_expectations
=> custom asserts

piperider_cli/cli.py
=> Move stages from option to argument

piperider_cli/__init__.py, piperider_cli/cli.py, piperider_cli/custom_assertion.py
=> Support working dir

piperider_cli/stage_runner.py
=> [Feature] Refactor piperider-cli run output message

piperider_cli/cli.py, piperider_cli/stage_runner.py
* merge report to one json in-memory and send the report to API server
* support metadata attaching to the report
```sh
$ export PIPERIDER_SERVICE_URL=http://127.0.0.1:8000
$ piperider-cli run stages/local.yaml --metadata external_url=https://github.com/InfuseAI/piperider-cli/actions/runs/2166137630
```
*  when `PIPERIDER_SERVICE_URL` is set, CLI will upload the reports to our service
* `--metadata` could be short `-m`
```sh
/Users/qrtt1/temp/piperider-cli/venv/bin/python /Users/qrtt1/temp/piperider-cli/venv/bin/piperider-cli run \
stages/local.yaml -m external_url=https://github.com/
Process stage [local:input]
Calculating Metrics: 100%|██████████| 2/2 [00:00<00:00, 240.71it/s]
Calculating Metrics: 100%|██████████| 21/21 [00:00<00:00, 686.77it/s]
Test Report: …
```
=> Upload reports to PipeRider service

piperider_cli/stage_runner.py
=> Fix aggregated report

piperider_cli/__init__.py, piperider_cli/cli.py, piperider_cli/stage_runner.py, setup.py
* Use rich library to handle the CLI output
Signed-off-by: Kent Huang <kentwelcome@gmail.com>
=> [Feature] sc-25771 make CLI console output more beautiful

piperider_cli/__init__.py, piperider_cli/cli.py, piperider_cli/data/__init__.py, piperider_cli/data/convert_to_exp.py, piperider_cli/stage.py, piperider_cli/stage_runner.py, piperider_cli/ydata/__init__.py, setup.py
- extract class Stage and StageFile into stage.py
Signed-off-by: Kent Huang <kentwelcome@gmail.com>
=> [Refactor] move _run_stage logic into stage object

piperider_cli/profiler/__init__.py, piperider_cli/profiler/profiler.py
Usage
```
from piperider_cli.profiler import Profiler
import sqlalchemy
import os
user= os.getenv("SNOWFLAKE_USER")
password= os.getenv("SNOWFLAKE_PASSWORD")
account=os.getenv("SNOWFLAKE_ACCOUNT")
database="INFUSE_FINANCE"
schema="PUBLIC"
warehouse="COMPUTE_WH"
engine = sqlalchemy.create_engine(f"snowflake://{user}:{password}@{account}/{database}/{schema}?warehouse={warehouse}")
profiler = Profiler(engine)
result = profiler.profile()
import json
print(json.dumps(result, indent=4))
with open('report.json', 'w') as f:
f.write(json.dumps(result, indent=4))
```
=> Implement the profiler

piperider_cli/profiler/profiler.py
=> add processing time of profiling a column

piperider_cli/workspace.py
=> Store table reports in separate files

piperider_cli/profiler/profiler.py, tests/profiler/test_profiler.py
- Add unittest
- Change the range calculation
=> Add unittest for Profiler and enhance profiler

README.md
Signed-off-by: DB  [db@infuseai.io](mailto:db@infuseai.io)
PipeRider's existing README is not reflecting to the new shape the team is developing, modify the README file to match current development status
`README.md`: added PIpeRider's narrative and it's commands
=> [Feature] sc-25772 refine README to match current development status

piperider_cli/profiler/profiler.py, tests/profiler/test_profiler.py
Usage
```
profiler = Profiler(engine)
result = profiler.profile(tables=["test1"])
```
=> Profiler: support options for tables

.github/workflows/pypi.yaml
=> Add pypi action

piperider_cli/assertion_engine/assertion.py
=> [Fix] sc-26025 handle expected values include datetime

piperider_cli/workspace.py
=> [Feature] sc-25905 create symlink pointing to latest output directory

piperider_cli/profiler/profiler.py, tests/profiler/test_profiler.py
Integer and numeric have slightly different logic
1. Don't show fraction. numeric `5.0 _ 10.0` => integer `5 _ 10`
2. If the range is 1, don't show range `1 _ 2` => `1`, `10 _ 11` => `11`
=> distribution for integer

piperider_cli/profiler/profiler.py, tests/profiler/test_profiler.py
=> enhance datetime distribution by its range

piperider_cli/assertion_engine/assertion.py, piperider_cli/cli.py, piperider_cli/workspace.py
=> [Feature] sc-26122 Show the run summary for each tables

piperider_cli/cli.py, piperider_cli/workspace.py
- If the datasource is provided by dbt, check catalog file contents
- Ask user to run 'dbt docs generate' command if not catalog file found
=> [Fix] sc-25905 check dbt catalog file in debug and run commands

piperider_cli/profiler/profiler.py, piperider_cli/workspace.py
=> [Fix] sc-26131 support multiple schema when using dbt on postgres

piperider_cli/profiler/profiler.py
=> add boolean type profiling

piperider_cli/workspace.py
=> [Feature] sc-26142 change dbt root and profile to support relative path

piperider_cli/cli.py, piperider_cli/workspace.py
=> [Feature] sc-26152 enhance debug console output

README.md
Signed-off-by: DB [db@infuseai.io](mailto:db@infuseai.io)
We have pypi package now, change the installation instruction in README
`README`'s installation section
=> [Feature] sc-25772 update installation instruction in README

setup.py
Remove the connector dependencies
- snowflake
- postgres
=> remove connector dependencies

piperider_cli/profiler/profiler.py, tests/profiler/test_profiler.py
- fix date profiling column type
- adjust date range
=> fix sqlite date profiling and adjust date range decision

piperider_cli/__main__.py, piperider_cli/workspace.py
Add the sqlite option in init command
=> add sqlite option in init command

piperider_cli/workspace.py
Make it more consistent with `dbt run`
```
usage: dbt run [--project-dir PROJECT_DIR] [--profiles-dir SUB_PROFILES_DIR] [--profile PROFILE] [-t TARGET]
optional arguments:
--project-dir PROJECT_DIR
Which directory to look in for the dbt_project.yml file. Default is the current working directory and its parents.
--profiles-dir SUB_PROFILES_DIR
Which directory to look in for the profiles.yml file. Default = /Users/popcorny/.dbt
--profile PROFILE     Which profile to load. Overrides setting in dbt_project.yml.
-t TARGET, --target TARGET
Which target to load for the given profile
```
```
dataSources:
- name: infuse_finance
type: snowflake
dbt:
project: infuse_finance
target: dev
profile: ~/.dbt/profiles.yml    
root: .
```
```
dataSources:
- name: infuse_finance
type: snowflake
dbt:
profile: …
```
=> make the piperider dbt configuration more consistent with dbt config

piperider_cli/workspace.py
dbt search would ignore file in `dbt_packages` folder
=> dbt search ignore file in dbt_packages

piperider_cli/workspace.py
=> fix compatibility for debug command

piperider_cli/cli.py, piperider_cli/compare_report.py, piperider_cli/workspace.py, setup.py
- User can use command line option '--input-a' and '--input-b' to select
profiler outputs by CLI directly.
- If no files provided by CLI options. We will ask user to select 2 output files
by interactive checkbox.
- If users only provid one file by CLI option. We will ask user to
select 1 output file by interactive list.
=> [Feature] sc-25910 Implement TUI to let users select reports to compare

.github/workflows/pypi.yaml, Dockerfile, piperider_cli/cli.py, setup.py
=> [Feature] integrate with sentry

.github/workflows/pypi.yaml, Dockerfile
=> [Fix] Release github action

piperider_cli/compare_report.py, piperider_cli/hack/inquirer.py, setup.py
Co-authored-by: Ching-Yi Chan <qrtt1@infuseai.io>
=> [Feature] sc-25910 hack the upstream library inquirer without fork it

.github/workflows/pypi.yaml, piperider_cli/cli.py
=> [Feature] add sentry release and environment

piperider_cli/assertion_engine/assertion.py
=> Fix wrong plugins path

docs/assertions/assert_column_exist.md, docs/assertions/assert_column_in_types.md, docs/assertions/assert_column_max_in_range.md, docs/assertions/assert_column_min_in_range.md, docs/assertions/assert_column_not_null.md, docs/assertions/assert_column_null.md, docs/assertions/assert_column_type.md, docs/assertions/assert_column_unique.md, docs/assertions/assert_row_count.md
=> Add docs for builtin assertions

README.md, piperider_cli/workspace.py, setup.py
1. docs for installation connectors
2. show hints for users
=> Add connector installation doc and cli messages

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
* add PR template 
* update contributing doc
=> Add OSS needed documentation

piperider_cli/configuration.py, piperider_cli/datasource.py, piperider_cli/workspace.py
- Refactor user input function by inquirer
- Refactor DataSource field to support default value and optional
- Refactor workspace to extract DataSource and Configuration to other
files
=> [Feature] sc-26163 Ask user to fill credentials in non dbt case

Dockerfile
=> rollback packages for piperider-action image

README.md, piperider_cli/datasource.py, setup.py
enhancement
Release to the `piperider` PYPI (previous was `piperider-cli`)
sc-26426
=> Update package name to piperider

piperider_cli/cli.py, piperider_cli/event/track.py
=> Add tracked commands

setup.py
=> fix the jinja2 dependency

piperider_cli/data/piperider-init-template/.gitignore
Add `comparisions/` and `__pycache__/` to `.gitignore` template
=> Refine the .gitignore template

.flake8, .github/workflows/flake8.yaml, Makefile, piperider_cli/assertion_engine/assertion.py, piperider_cli/cli.py, piperider_cli/compare_report.py, piperider_cli/configuration.py, piperider_cli/datasource.py, piperider_cli/profiler/__init__.py, piperider_cli/profiler/profiler.py, piperider_cli/workspace.py
Use flake8 to check the python coding style
Add flake8 in Makefile and fix all the errors and warnings
sc-26390
=> [Feature] sc-26390 Add flake8 lint with github action

README.md
Update readme
Update document
N/A
=> [Update] add some bedges into Readme

README.md
Update readme
Add support Python version badge in README 
N/A
=> Add python support versions into README

README.md
Document update
Update README
N/A
=> [Update] remove typo in readme

piperider_cli/cli.py, piperider_cli/configuration.py, piperider_cli/error.py, piperider_cli/workspace.py
Enhance error message
- Implement user-defined Exceptions for piperider common errors
sc-26436
=> [Fix] sc-26436 Tell user to run init command if run without init

piperider_cli/cli.py, piperider_cli/datasource.py
Enhance wording
- Change `init` wording: 'Which data source would you like to connect to?'
- Rename `debug` command to `diagnose`
sc-26446
=> [Fix] update wording of init command, rename debug command to diagnose

.github/workflows/pypi.yaml, piperider_cli/cli.py, piperider_cli/configuration.py, piperider_cli/data/CONFIG, piperider_cli/data/piperider-init-template/.gitignore, piperider_cli/datasource.py, piperider_cli/event/__init__.py, piperider_cli/event/collector.py, piperider_cli/event/track.py, setup.py
=> Implement event collection

.flake8, piperider_cli/cli.py, piperider_cli/event/track.py
Enhancement
Handle exception in track command wrap
=> Handle command exception in track command wrap

piperider_cli/cli.py, piperider_cli/workspace.py
Enhance user experience
- Warn users and ask them to confirm if they run the `init` command under or upper the home director on the macOS platform.
sc-26438
=> [Feature] sc-26438 warn user if init command is running under home dir

piperider_cli/compare_report.py
Update UX
Add a hint message when comparing report
sc-26520
=> [Update] add hint when compare report

README.md
Document fix
Change readme markdown syntax of image URL, to support non GitHub platform
N/A
=> [Fix] Update README.md to support non GitHub platform

.github/workflows/nightly.yaml
Fix github action nightly build
Change to use other pypirc from github action secrtet
N/A
=> [Fix] change to use other pypirc from github action secret

piperider_cli/assertion_engine/__init__.py, piperider_cli/assertion_engine/assertion.py, piperider_cli/error.py, piperider_cli/workspace.py
- [v] Ensure you have added or ran the appropriate tests for your PR.
- [v] DCO signed
Enhancement
Add error message for wrong assertion configuration
sc-26574
=> Add error message for wrong assertion configuration

piperider_cli/assertion_engine/__init__.py
Enhancement
- Verify assertion configurations
- Add error messages
sc-26488
=> Verify assertion configurations and add error messages.

piperider_cli/configuration.py, piperider_cli/event/__init__.py
Enhancement
Use `telemetry.id` instead of `id`
=> Change telemetry structure in config

piperider_cli/assertion_engine/__init__.py
=> Fix wrong conditional

piperider_cli/assertion_engine/__init__.py, piperider_cli/assertion_engine/assertion.py, tests/test_builtin_assertions.py, tests/test_user_defined_assertions.py
1. When given a specified table, PipeRider only runs corresponding tests.
2. Given table name can be case insensitive in sqlite.
fix the bug that runs all tests.
sc-26508
- tested with the sqlite project
=> Fix run all assertions when given specified table

.github/workflows/nightly.yaml
Fix CI/CD
Fix manually trigger nightly build
=> [Fix] Fix nightly build

piperider_cli/error.py, piperider_cli/workspace.py
Enhancement
Replace 'catalog.json' with 'manifest.json' for fetching dbt information
sc-26469
=> Replace 'catalog.json' with 'manifest.json' for fetching dbt information

.github/workflows/e2e.yaml
enhancement
fixed the track id
See the new id
=> Use a static track-id for e2e

setup.py
Co-authored-by: simonliu1 <simonliu@infuseai.io>
bugfix
Our implementation is working after sqlalchemy `1.4`
sc26692
=> Add version reqirement for SQLAlchmey

piperider_cli/assertion_engine/assertion.py, piperider_cli/workspace.py
Enhancement
Ensure table and column names are case-sensitive
=> Feature/sc 26698/ensure table and column names are case sensitive

piperider_cli/profiler/profiler.py, setup.py
As title, make sqlalchemy 1.3 work
=> Support sqlalchemy 1.3

.github/workflows/tests.yaml
=> Add sqlalchemy tests

e2e-tests/testsuite/getting-started/002-compare.exp
=> Add result to the comparsion steps

.github/workflows/nightly.yaml
Fix CI/CD
Set version into github action steps outputs
n/a
=> [Fix] set version in github action steps outputs

piperider_cli/assertion_engine/assertion.py, piperider_cli/assertion_engine/recommended_rules/__init__.py, piperider_cli/assertion_engine/recommended_rules/table_assertions.py, piperider_cli/assertion_engine/recommender.py
1. add recommended assertion rules
2. add recommended assertions summary
to recommend assertions
sc-26477
None
=> add recommended assertion rules

piperider_cli/cli.py
Enhancement
Refine help text in cli
sc-26683
=> Refine help text in cli

docs/assertions/assert_column_in_range.md, docs/assertions/assert_column_max_in_range.md, docs/assertions/assert_column_min_in_range.md, piperider_cli/assertion_engine/__init__.py, tests/test_builtin_assertions.py
enhancement
introduce new assertion function
sc-26659
=> Add assert_column_in_range

piperider_cli/assertion_engine/recommended_rules/__init__.py, piperider_cli/assertion_engine/recommended_rules/recommender_assertion.py, piperider_cli/assertion_engine/recommended_rules/table_assertions.py, piperider_cli/assertion_engine/recommender.py
refactor 
refactor the import part of recommended assertions
sc-26479
=> [Refactor] import recommended assertions rules

.github/workflows/nightly.yaml
Fix CI/CD
Fix typo in nightly.yaml github action
n/a
=> [Fix] typo in nightly build github action

piperider_cli/cli.py
Bug fix
- use regex to parse nightly build version format
n/a
=> [Fix] fix the logic of paring sentry environment

piperider_cli/assertion_engine/assertion.py, piperider_cli/assertion_engine/recommended_rules/table_assertions.py, piperider_cli/workspace.py
Feature
1. add non-null recommended assertions
2. check recommended assertion files existing
sc-26478
NONE
=> add non-null recommended assertions

piperider_cli/compare_report.py, piperider_cli/datasource.py
Bug fix
- fix python-inquirer can not use backspace on Linux
sc-26693
=> [Fix] sc-26693 fix python-inquirer can not use backspace on Linux

docs/assertions/assert_column_schema_type.md, docs/assertions/assert_row_count.md, piperider_cli/assertion_engine/__init__.py, piperider_cli/assertion_engine/recommended_rules/table_assertions.py
Feature
- Modify the logic of generate min test functions
- Add 2 build-in test functions. `assert_row_count` and
`assert_column_schema_type`
- Add 2 recommended assertion rules to create test case for
`assert_row_count` and `assert_column_schema_type`
sc-26477
=> [Feature] sc-26477 update recommended assertion rules

piperider_cli/assertion_engine/assertion.py
Bugfix
- Inherit the existing assertions if no new recommended assertions are found. Usually caused by renaming column
sc-26984
=> [Fix] sc-26984 handle column renamed issue when generate-assertions

piperider_cli/workspace.py
Bugfix/Enhancement
Parsing dbt resource information with dbt list command instead of dbt manifest.json.
sc-26958
=> Get dbt tables from dbt command instead of manifest.json.

.github/workflows/e2e.yaml, e2e-tests/testsuite/getting-started/001-run.exp
enhancement
* try to reduce cost by flaky tests
* more information when failed
=> Set timeout and enabling debug information

piperider_cli/workspace.py
Fix
* Get dbt tables from dbt command instead of manifest.json.
* Refactor assembling dbt test command.
* Get column info from dbt_resources
* Fix schema info
* Fix dbt resources
sc-26958
=> Get dbt tables from dbt command instead of manifest.json. (#185)

piperider_cli/workspace.py
Bugfix
- Load assertions from profiling results instead of profiler metadata
sc-27018
=> [Fix] sc-27018 fix all assertions will always be executed in postgresql

piperider_cli/workspace.py
Bugfix
* [Fix] sc-27018 fix all assertions will always be executed in postgresql
* [Fix] flake8 issue
sc-27018
=> [Cherry-pick] sc-27018 fix all assertions will always be executed in postgresql

docs/user-defined-test-function.md, piperider_cli/assertion_engine/assertion.py, piperider_cli/data/piperider-init-template/plugins/customized_assertions.py, tests/_user_defined_assertion_functions.py, tests/test_user_defined_assertions.py
enhancement
migration user-defined assertion function to our new design
sc-26630
=> Rewrite user-defined assertion function for new design

piperider_cli/cli.py, piperider_cli/configuration.py, piperider_cli/workspace.py
Enhancement
Replace --skip-dbt with --dbt-test and --dbt-build, which eliminates potential performance issues.
sc-27024
=> Replace --skip-dbt with --dbt-test and --dbt-build

piperider_cli/cli.py, piperider_cli/error.py, piperider_cli/workspace.py
Enhancement
Remove dbt manifest related methods
=> Remove dbt manifest related methods

piperider_cli/workspace.py
Bugfix
Refind the way to check dbt command
=> Refactor dbt command check

piperider_cli/cli.py, piperider_cli/event/track.py, piperider_cli/guide.py
enhancement
help users get started
sc-26888
=> Implementation the next step guide

.github/workflows/nightly.yaml, piperider_cli/cli.py
Enhancement
Add commit sha to version output if env is not production
=> Add commit sha to version output

piperider_cli/profiler/profiler.py, tests/profiler/test_profiler.py
Feature
[Problem]
Original problem, the histogram min, max is far from original min max.
For example, the example data is `0.6 ~ 510`, but the histogram range would be `0 ~ 1000`. And there would a lot of empty bins from `550 ~ 1000`
[Solution]
Adjust the histogram logic
1. The bin edge to `[1, 2, 2.5, 5] * 10^n`  grid  =>  Just `min + i * interval`, and `interval = (max - min) / buckets`
2. The range from `(adj_min, adj_max)` => `(min, max)`
3. Bin number `20` => `50`
The behavior is similar to pandas profiling.
**Does this PR introduce …
=> Adjust the histogram logic

piperider_cli/cli.py, piperider_cli/configuration.py, piperider_cli/workspace.py
Cherry-pick
Replace --skip-dbt with --dbt-test and --dbt-build #200
sc-27024
=> [Cherry-pick] sc-27024 Replace --skip-dbt with --dbt-test and --dbt-build #200

piperider_cli/cli.py, piperider_cli/error.py, piperider_cli/workspace.py
Cherry-pick
Remove dbt manifest related methods (#203)
sc-27001
=> [Cherry-pick] sc-27001 Remove dbt manifest related methods (#203)

piperider_cli/assertion_engine/recommended_rules/table_assertions.py
Cherry pick
Fix recommending range assertions in wrong format #208
sc-27062
=> [Cherry Pick] sc-27062 Fix recommending range assertions in wrong format #208

piperider_cli/configuration.py, piperider_cli/datasource.py
Co-authored-by: Ching-Yi Chan <qrtt1@infuseai.io>
Bugfix
- Throw error if user defined both 'pass' and 'password' in profile.yml
sc-27076
=> [Fix] sc-27076 support pass in dbt profile.yaml

piperider_cli/workspace.py
Enhancement
Add dbt description to profiling result.
sc-26690
=> Add dbt description to profiling result

piperider_cli/configuration.py, piperider_cli/datasource.py
Cherry-pick
[Fix] sc-27076 support pass in dbt profile.yaml #214
sc-27076
=> [Cherry pick] sc-27076 support pass in dbt profile.yaml #214

.github/scripts/deploy_notify.sh, .github/workflows/nightly.yaml, .github/workflows/pypi.yaml
Feature enhance CI/CD
- Add deploy_notify.sh for nightly build
sc-26991
=> [Feature] sc-26991 Add deploy_notify.sh script for nightly build

.github/scripts/deploy_notify.sh, .github/workflows/nightly.yaml, .github/workflows/pypi.yaml
Cherry-pick
Add deploy_notify.sh script for nightly build #211
sc-26991
=> [Cherry pick] sc-26991 Add deploy_notify.sh script for nightly build #211

.github/workflows/pypi.yaml
Bugfix
Fix typo in github action yaml
sc-26991
=> Fix typo in github action

piperider_cli/workspace.py
Enhancement
Refine dbt test format
=> Refine dbt test format and validation

e2e-tests/testsuite/getting-started/002-compare.exp
Bugfix
Fix e2e compare-reports hang
=> Fix e2e compare-reports hang

.github/workflows/nightly.yaml
Bugfix
add GITHOB_TOKEN in env for fetching github data
sc-26991
=> [Bugfix] sc-26991 add GITHOB_TOKEN in env for fetching github data

README.md
Signed-off-by: Dave Flynn <analogue40@gmail.com>
=> Add PIpeRider blog link

piperider_cli/assertion_engine/assertion.py, piperider_cli/assertion_engine/recommender.py, piperider_cli/workspace.py
Feature
Add assertion description
=> Feature/sc 26690/add assertion description and show on report

piperider_cli/profiler/profiler.py
bug
profiler robustness issues on sqlite db
sc-27099
NONE
=> enhance profiler robustness on sqlite

.github/workflows/build-statics.yaml
quickfix for gitflow action build-statics
=> fix: build-statics.yaml syntax error

.github/workflows/e2e.yaml, piperider_cli/profiler/schema.json, piperider_cli/workspace.py, setup.py
Enhancement
Define single-report json schema
**To reviewer**
* Please merge it after `PR 222` got merged
* The e2e errors are expected because there are old data but new schema.
=> Chore/sc 26918/ts typedef

static_report/src/components/SingleReport/SingleReport.tsx
=> fix(single-report): remove flex-start attribute

.github/workflows/build-statics.yaml
=> fix: using npm commands running build

.github/workflows/pypi.yaml
Fix CI/CD
- Sleep 30 seconds before building the docker image. Let pypi.org update ready.
- Add build docker image as the second job of release process
sc-27205
=> [Fix] sc-27205 Extract build docker image

piperider_cli/cli.py, piperider_cli/dbt_adapter.py, piperider_cli/workspace.py
Enhancement
Separate dbt adaptor from workspace
=> Separate code for dbt adaptor

static_report/src/components/ComparisonReport/CRTableColumnDetails.tsx, static_report/src/components/SingleReport/SRTableColumnDetails.tsx, static_report/src/components/shared/MetrisInfo.tsx, static_report/src/utils/index.tsx
feature added
show the most common value for string column
sc-26885
=> Show most common at string column

static_report/src/components/ComparisonReport/CRList.tsx, static_report/src/components/ComparisonReport/CRTableColumnDetails.tsx, static_report/src/utils/index.tsx
- Fixed [sc27196](https://app.shortcut.com/infuseai/story/27196/handling-unexpected-issues-when-column-name-changes)
=> fix(comparison): handling unexpected columns name change

piperider_cli/profiler/profiler.py
bug
overflow when calculating square average
sc-27214
NONE
=> fix square average overflow

static_report/src/components/SingleReport/SRTableColumnDetails.tsx, static_report/src/utils/index.tsx
=> fix(comparison): return dash when value is null

static_report/src/components/SingleReport/SRList.tsx, static_report/src/components/SingleReport/SRTableColumnDetails.tsx
Feature
Show description in single report
=> Add description icon to table and column

.github/workflows/nightly.yaml
Bugfix
- checkout git repo with fetch-depth = 0
sc-27244
=> [Fix] sc-27244 fix nightly build shortcut integration

piperider_cli/profiler/profiler.py
bug
profiling`date` column returns `datetime` after `date_trunc` in postgresql
sc-27202
NONE
=> fix type error of comparing datetime to date

piperider_cli/assertion_engine/recommended_rules/table_assertions.py
Bugfix
- Fix None type object access issue in the recommended assertion functions
sc-27246
=> [Fix] sc-27246 Fix recmomended assertion issues

static_report/src/components/ComparisonReport/ComparisonReport.tsx, static_report/src/components/SingleReport/SRList.tsx, static_report/src/components/SingleReport/SingleReport.tsx, static_report/src/utils/index.tsx
- Due to the schema name change, so got the wrong assertions number
=> fix(assertions): update fields name and fix layout

static_report/src/components/SingleReport/SRTableColumnDetails.tsx
=> Make typescript happy

static_report/src/components/SingleReport/SingleReport.tsx
Bugfix
Remove unused vars to make CI work
=> Remove unused vars

.github/workflows/build-statics.yaml
Chore
Require build upon each PR event, for build checks
sc 27299
NO
=> update: build on every PR; Commit build only upon merge event

.github/workflows/pypi.yaml
=> fix: typo in pypi.yaml

static_report/src/components/ComparisonReport/CRTableColumnDetails.tsx, static_report/src/components/SingleReport/SRTableColumnDetails.tsx, static_report/src/components/shared/NumericTableColumn.tsx
…ties shown
Fix
Restore missing numeric values
=> fix: Restore missing numeric properties (merge UI to shared comp)

static_report/src/components/ComparisonReport/CRTableColumnDetails.tsx, static_report/src/components/SingleReport/SRTableColumnDetails.tsx, static_report/src/components/shared/GeneralTableColumn.tsx
Chore refactor
To share UIs -- less room for missed updates in dev
N/A
NO
=> refactor: general-table-column (shared UI)

piperider_cli/dbt_adapter.py
=> Fix empty description from dbt

piperider_cli/configuration.py, piperider_cli/error.py
Bugfix
- Handle the error when load dbt project and profile
sc-27203
=> [Fix] sc-27203 Handle the error when load dbt project and profile

piperider_cli/profiler/profiler.py
Chore
- Make the Profiler more structured
- Add mismatched metric in the bool column profiler
=> Chore: Refactor the profiler

piperider_cli/datasource.py, piperider_cli/workspace.py
feature
- Verify snowflake connector by importing both snowflake.sqlalchemy &
snowflake.connector
sc-27306
=> Feature: sc-27306 Check datasource connector before run

static_report/src/components/ComparisonReport/CRTabSchemaDetails.tsx
=> fix(comparison): typo

piperider_cli/profiler/__init__.py, piperider_cli/profiler/event.py, piperider_cli/profiler/profiler.py, piperider_cli/profiler/schema.json
Feature
Add event handler in the profiler. So the client of `Profiler` can use its way to show the profiling result
=> Add profiler event handler

piperider_cli/profiler/profiler.py
Chore
1. refactor date column distribution
2. add a base method to get database backend name
sc-27304
NONE
=> Refactor date distribution and backend type

piperider_cli/assertion_generator.py, piperider_cli/cli.py, piperider_cli/workspace.py
Refactor
- Remove generate assertions code from workspace.py
sc-27426
=> Feature/sc 27426/clean up workspace generate assertions

.github/workflows/build-statics.yaml, .github/workflows/ci-statics.yaml
Fix for github workflow condition not firing. This splits a separate workflow for when PR gets updated and PR gets merged.
=> add ci-statics.yaml for separate workflow (PR open, synch)

static_report/src/components/ComparisonReport/CRTableOverview.tsx, static_report/src/components/ComparisonReport/ComparisonReport.tsx, static_report/src/components/SingleReport/SRList.tsx, static_report/src/components/SingleReport/SRTableOverview.tsx, static_report/src/components/SingleReport/SingleReport.tsx, static_report/src/hooks/useComparisonChart.ts, static_report/src/hooks/useSingleChart.ts, static_report/src/sdlc/single-report-schema.d.ts, static_report/src/utils/chart.ts, static_report/src/utils/index.tsx
- Fixed assertions result. If the dbt assertions exist should aggregate with the pipe rider assertions.
=> fix(assertions): aggregate piperider and dbt assertions result

piperider_cli/configuration.py, piperider_cli/datasource.py, piperider_cli/error.py, piperider_cli/event/track.py, piperider_cli/runner.py, piperider_cli/validator.py
Refactoring
- Enhance piperider exception handling
- Add hint into PiepRiderError class
sc-27269
=> Feature: sc-27269 enhance piperider exception handling

piperider_cli/runner.py
Feature
Enhance error handling when profiler encounter error
sc-27421
=> Feature: sc-27421 enhance error handling when profiler encounter error

piperider_cli/profiler/profiler.py, piperider_cli/profiler/schema.json, tests/profiler/test_profiler.py
** PR checklist**
Chore
- Fix datetime mismatched rule
- Change the way to query mismatch data.
- Add datetime and bool column unittest
- Add docstring
=> Feature/sc 27304/refactor the profiler

piperider_cli/adapter/__init__.py, piperider_cli/cli.py, piperider_cli/runner.py, piperider_cli/validator.py, tests/runner/test_runner.py
Fix
```
ModuleNotFoundError: No module named 'piperider_cli.adapter'
```
=> Fix no module named 'piperider_cli.adapter' problem

piperider_cli/runner.py
Refactor the layout of input/output
Use rich table to display the assertions result and assertion summary
sc-27300
=> [Feature] Modify the layout of assertions result

piperider_cli/profiler/profiler.py
bug
fix quantile calculation of sqlite
sc-27495
NONE
=> fix quantile calculation

piperider_cli/profiler/schema.json, piperider_cli/runner.py
Bugfix
Remove null properties from column results to prevent frontend crashing
=> Remove null properties from column results

piperider_cli/profiler/profiler.py, tests/profiler/test_profiler.py
feature
enhance sqlite string column mismatch handler
sc-27501
https://www.sqlite.org/datatype3.html#type_affinity
> A column with TEXT affinity stores all data using storage classes NULL, TEXT or BLOB. If numerical data is inserted into a column with TEXT affinity it is converted into text form before being stored.
NONE
=> feature: add string column mismatch handler

static_report/src/utils/assertion.ts
Bugfix
Fix inconsistent test status
=> Fix test status calculation

setup.py
Bug fix (workaround)
In snowflake, it would show 
=> Workaround for sqlalchemy problem

piperider_cli/cli.py, piperider_cli/compare_report.py
Enhancement
Rename base/input to base/target in TUI
=> Rename base/input to base/target in TUI

piperider_cli/assertion_engine/assertion.py, piperider_cli/runner.py
bug
It's possible that assertion files have a key but lack content.
Hence, this PR is to prevent getting a `NoneType` object in such a case.
sc-27559
NONE
=> fix: add empty assertion content handler

piperider_cli/assertion_engine/assertion.py, piperider_cli/compare_report.py, piperider_cli/datasource.py
Bugfix
- In some platforms (ex. Windows) python-inquirer doesn't support it very well. 
Change to use rich.console to collect input value at those platforms.
sc-27581
https://github.com/InfuseAI/piperider/issues/298
=> [Feature] sc-27581 Collect user input wihtout using lib py-inquirer

piperider_cli/event/__init__.py
Enhance
Add 'init' comment to the event log whitelist 
sc-27640
=> [Enhance] sc-27640 Add 'init' comment to the event log whitelist

piperider_cli/profiler/profiler.py
Bugfix
- Failed in colab environment.
- The sqlite version is 3.22.0 in colab, but window function is only supported in >3.25.0
- 
=> Fix quantile issue in colab environment

.github/workflows/nightly.yaml, piperider_cli/cli.py, piperider_cli/event/__init__.py, piperider_cli/event/collector.py, piperider_cli/event/track.py, piperider_cli/runner.py
Feature
Collect more information in the telemetry collector
sc-27680
=> [Feature] sc-27680 Collect more inforamtion in telemery collector

piperider_cli/event/collector.py
Feature added
Add track property to know an execution was done by human or non-human
sc-27660
=> [feat] Mark the command execution automatically or manually

piperider_cli/assertion_engine/assertion.py, piperider_cli/assertion_engine/recommended_rules/table_assertions.py
bug
1. recommended assertions rule division by zero
2. may throw IllegalStateAssertionError when a result actual value is 0
sc-27693
NONE
=> fix: recommend assertion rule division by zero

static_report/src/components/ComparisonReport/CRTabProfilingDetails.tsx, static_report/src/components/SingleReport/SRTabProfilingDetails.tsx, static_report/src/sdlc/generate-comparisons.sh, static_report/src/utils/formatters.tsx
Fix for broken UI when `distribution` is not provided
UI breaks in cases when distribution is not provided
N/A
https://user-images.githubusercontent.com/11186480/181156872-5451fc3a-13d7-4269-b6b9-590d39f2699a.mov
=> [Bug] type guard optional distribution field

static_report/src/components/shared/GeneralTableColumn.tsx
ui fix
wrong column info was shown (valid)
Fixed version:
Yes
Fixed wrong column detail display of `valid`
=> fix: valid count was incorrect

.github/scripts/bump_amplitude_release.sh, .github/workflows/nightly.yaml, .github/workflows/pypi.yaml
Feature
Bump release version on Amplitube
sc-27694
=> [Feature] sc-27694 Bump release version on Amplitude

.github/PULL_REQUEST_TITLE_CHECKER.json, .github/workflows/pr.yaml
Chroe
Apply PR title checker and make sure all the PR will follow title name convention.
sc-27700
=> [Chore] sc-27700 Apply PR title checker

piperider_cli/cli.py, piperider_cli/compare_report.py
Feature
* User can specify a datasource
* User can compare the last two reports without manual selection
=> [Feature] Add --last and --datasource to compare-reports

piperider_cli/__init__.py, piperider_cli/cli.py, piperider_cli/compare_report.py, piperider_cli/generate_report.py, piperider_cli/runner.py
feature added
Make users being able to set the output location (a directory path)
sc-27660
=> [Feature] Support to set the output location

.github/workflows/nightly.yaml, .github/workflows/pypi.yaml
Bug
Fix typo in github action config files
sc-27694
=> [Bug] sc-27694 Fix wording issue in github action

piperider_cli/assertion_engine/assertion.py, piperider_cli/runner.py
Feature
Add assertion analysis to telemetry data
sc-27510
=> [Feature] Add assertion analysis to telemetry data

piperider_cli/cli.py, piperider_cli/compare_report.py, static_report/src/sdlc/generate-comparisons.sh
Bugfix
- PipeRider 'compare-reports' command will generate
'comparison_data.json' file when '--debug' flag is set
sc-27731
=> [Bug] sc-27731 Fix frontend e2e test failed issue

piperider_cli/profiler/profiler.py, piperider_cli/profiler/schema.json, tests/profiler/test_profiler.py
feature
- Add text length analytics metric: For text column, add min, max, average, standard deviation for text length
- For text, integer column: Add duplicates and non-duplicates count.
- Add more data composition metrics
- Text column: count of zero-length text, non-zero-length text
- Integer, numeric column: count of zeros, positive values, negative values.
- Bool column: count of true values, false values
- For integer column, add the top-k metrics
sc-27431
NONE
=> [Feature] Add text length analytics, duplicates, data composition metrics

piperider_cli/generate_report.py
Bugfix
Remove redundant print
sc-27727
=> [Bug] sc-27727 Remove redundant print

setup.py
Bugfix
Add SENTRY_DNS file in setup.py package_data field
Otherwise, piperider can not launch successfully
sc-27727
=> [Bug] sc-27727 Add SENTRY_DNS file in setup.py package_data field

piperider_cli/profiler/profiler.py
Bug
Current
1,000,000,000 -> t
1,000,000,000,000 -> b
Expected
1,000,000,000 -> b
1,000,000,000,000 -> t
=> [Bug] Fix wrong number format

docs/metrics.md
=> [Document] Add metric document

piperider_cli/profiler/schema.json
Chore
1. Make the metric-related field as optional
2. Make the description as optional
3. The schema type should not have `date` and `time`
=> [Chore] Adjust the json schema

piperider_cli/assertion_engine/__init__.py, piperider_cli/assertion_engine/assertion.py, piperider_cli/assertion_engine/recommended_rules/__init__.py, piperider_cli/assertion_engine/recommended_rules/table_assertions.py, piperider_cli/assertion_engine/recommender.py, piperider_cli/assertion_engine/types/assert_column_misc.py, tests/orders_1k.json
chore
1. refined recommended assertion rules because new metrics were introduced.
2. refined import style
sc-27695
NONE
=> [Chore] Change to use the new metrics to recommendation logic

static_report/cypress/e2e/spec.cy.ts, static_report/cypress/tsconfig.json, static_report/package.json, static_report/src/components/shared/Main.tsx, static_report/src/components/shared/Sidebar.tsx, static_report/yarn.lock
https://user-images.githubusercontent.com/10325111/182556613-62214c29-f56c-4e46-8c81-61b825d4b29a.mp4
- added the sidebar
- added user feedback feature
=> [Feature] add sidebar and user feedback feature

piperider_cli/event/collector.py
enhancement
reduce one-time user-id in automation use cases
sc-27857
=> [Feature] Aggregate automation user data by project-id

piperider_cli/generate_report.py, static_report/src/sdlc/core.js, static_report/src/sdlc/global.d.ts
Feature
Pass amplitude project_id value to static report
sc-27510
=> [Feature] sc-27510 Pass project_id value to static report

README.md
Chore
Update sample reports in readme
=> [Chore] Update sample reports

static_report/.env.development, static_report/package.json, static_report/src/components/ComparisonReport/ComparisonReport.tsx, static_report/src/components/SingleReport/SingleReport.tsx, static_report/src/components/shared/Main.tsx, static_report/src/utils/amplitudeEvents.ts, static_report/yarn.lock
- Integrated amplitude for event tracking
=> [Feature] integrate amplitude

README.md
Chore
Update sample comparison report
=> [Chore] Update sample comparison report

piperider_cli/compare_report.py
Feature
To find the latest comparison report from the `latest` folder under the `.piperider/comparisons` folder
sc-27887
NONE
=> [Feature] Add a latest link to the latest comparison report

static_report/src/components/ComparisonReport/ComparisonReport.tsx, static_report/src/components/SingleReport/SingleReport.tsx, static_report/src/hooks/useAmplitudeOnMount.ts, static_report/src/utils/amplitudeEvents.ts
- When user into the report detail page, it should send an event for calculating purpose
=> [Bug] sending an event when user into a report page

static_report/src/components/shared/Sidebar.tsx
https://user-images.githubusercontent.com/10325111/183551575-424da971-6496-474d-9f30-0283929bdd84.mp4
- *As title*
=> [Chore] update feedback title and added optional email

static_report/src/components/shared/Sidebar.tsx
- Added email optional wording
=> [Chore] added email optional wording

piperider_cli/runner.py
Chore
remove a redundant artifact, `.profiler.json`
sc-27976
NONE
=> [Chore] remove a redunant artifact

piperider_cli/profiler/profiler.py
Feature
- Some other type does not support distinct in some database. Remove the distinct metric.
=> [Feature] Remove distinct metric from other type

static_report/src/components/shared/Main.tsx, static_report/src/utils/amplitudeEvents.ts
- Added user id for the amplitude to identify a user
=> [Bug] add user id for amplitude to identify users

README.md
add notes to connectors
Signed-off-by: Liang-Bin Hsueh <hlb@infuseai.io>
=> [Document] Update README.md

piperider_cli/profiler/profiler.py
feature
In the current release, the profiler cannot recognize the snowflake `timestamp_ntz` schema type.
We add this support in this PR.
sc-27838
NONE
=> [Feature] Support snowflake timestamp_ntz schema type

README.md
Signed-off-by: Eric Yang <ericy@infuseai.io>
before:
after:
=> [Document] Update README.md to correctly render table

Makefile, piperider_cli/server/__init__.py, piperider_cli/server/apis.py, piperider_cli/server/common.py, piperider_cli/server/reports.py, setup.py
Refactoring with flask blueprints
=> [Chore] Split modules by blueprints

README.md
Document
Update sample reports for version 0.6.0 in README
=> [Document] Update sample reports for version 0.6.0

piperider_cli/configuration.py, piperider_cli/datasource/__init__.py, piperider_cli/datasource/redshift.py, piperider_cli/error.py, piperider_cli/profiler/profiler.py, piperider_cli/validator.py, setup.py
Feature
Support RedShift datasource
sc-27801
=> [Feature] sc-27801 Init command support redshift

piperider_cli/datasource/bigquery.py
Bugfix
Change output format of gcloud command
sc-28110
=> [Bug] sc-28110 Change the output format of gcloud auth command

.github/workflows/e2e.yaml, piperider_cli/profiler/schema.json, piperider_cli/profiler/version.py, piperider_cli/runner.py
enhancement
The run.json will include new metadata:
* project_id
* user_id
* metadata_version: md5hex(schema.json)
* version: piperider version
```json
{
"version": "0.7.0.dev",
"project_id": "d43a9b48629c45f7a331c26fd26c89fb",
"user_id": "32e5d3ef2f894cd58adf27d1605995f5",
"metadata_version": "9479f4c38dc78926b0adf46461adb4fe",
"id": "d40f2f6554114a538617344a60d909f7",
"created_at": "2022-08-15T02:53:07.470638Z",
"datasource": {
"name": "demo",
"type": "sqlite"
}
}
```
=> [Feature] new metadata to single run report

piperider_cli/cli.py, piperider_cli/datasource/__init__.py, piperider_cli/datasource/survey.py, piperider_cli/feedback.py, piperider_cli/initializer.py, setup.py
Feature
- Ask user to fill what data source should we need to support
sc-29777
=> [Feature] sc-29777 Collect user feedback in CLI

.github/workflows/build-statics.yaml, static_report/package.json, static_report/yarn.lock
Chore
Previously all `close` PR events will trigger this workflow. This is to resolve the issue so that only upon merged event will the workflow get triggered.
N/A
=> [Chore] : build-statics (if_merged_build condition) + unneeded dependency cleanup

piperider_cli/datasource/survey.py, piperider_cli/initializer.py
Bugfix
- Fix init command will fail to generate config files without any error message.
sc-28220
=> [Bug] sc-28220 fix init command will fail to generate config files

.github/workflows/pypi.yaml
Improve release process
- Use github action repository dispatch to trigger other repo to build
reports
sc-28191
=> [Feature] sc-28191 Setup release script to auto generate sample reports

setup.py
Bugfix
Add `pytz` as required package for BigQuery.
Related issue: https://github.com/googleapis/python-bigquery-sqlalchemy/issues/475
sc-28217
=> [Bug] fix pybigquery package dependency

piperider_cli/cli.py, piperider_cli/datasource/__init__.py, piperider_cli/datasource/bigquery.py, piperider_cli/error.py, piperider_cli/event/track.py, piperider_cli/runner.py, piperider_cli/validator.py
Bugfix
- Remove bigquery default value of service account
- Throw error when no available table is found in the DB connection
- The CLI won't show the next step if the main function returns a non-0 value.
=> [Bug] sc-28245 Remove default value of bigquery service account

README.md
Update document
Update README connectors list 
sc-28246
=> [Release] Update PipeRider README connectors list

.github/workflows/pypi.yaml
BugFix
Update release process github token
sc-28246
=> [Release] sc-28246 Update release process github token

piperider_cli/datasource/__init__.py, piperider_cli/datasource/bigquery.py, piperider_cli/datasource/field.py, piperider_cli/error.py, piperider_cli/hack/datasource_inquirer_prompt.py
enhancement
make `init` easy for BigQuery
sc-27974
**Demos**
* OAuth https://asciinema.org/a/x2nqO8I6bMUHTNp0MNUUMcfNp
* Service Account https://asciinema.org/a/IABsSghvAQyFOYtwI0t4mASIg
=> [Feature] Refine the initialization flow for BigQuery

static_report/src/components/ComparisonReport/CRTabProfilingDetails.tsx, static_report/src/components/ComparisonReport/CRTabSchemaDetails.tsx, static_report/src/components/ComparisonReport/CRTableList/CRTableListAssertions.tsx, static_report/src/components/ComparisonReport/CRTableList/CRTableListColumnItem.tsx, static_report/src/components/ComparisonReport/CRTableList/CRTableListColumnList.tsx, static_report/src/components/ComparisonReport/CRTableList/CRTableListColumnsSummary.tsx, static_report/src/components/ComparisonReport/CRTableList/CRTableListRowsSummary.tsx, static_report/src/components/ComparisonReport/CRTableList/index.tsx, static_report/src/components/ComparisonReport/CRTableOverview.tsx, static_report/src/components/SingleReport/SRTableList/SRTableListColumnItem.tsx, static_report/src/components/shared/Charts/HistogramChart.tsx, static_report/src/types/index.ts, static_report/src/utils/assertion.ts, static_report/src/utils/transformers.tsx
=> [Bug] check base & target is undefined/null and fixed types

.flake8, piperider_cli/configuration.py, piperider_cli/datasource/__init__.py, piperider_cli/datasource/duckdb.py, piperider_cli/datasource/sqlite.py, piperider_cli/error.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, setup.py
Co-authored-by: Ching-Yi Chan <qrtt1@infuseai.io>
Feature
- Support load CSV file directly by using duckdb
- Support duckdb datasource
sc-27803
=> [Feature] sc-27803 Support CSV datasource by duckdb

piperider_cli/generate_report.py
Bugfix
Prevent script-injection in report page if the json payload contain `</script>`
sc-28278
=> [Bug] sc-28278 Encoded the json payload and decoded them in index.html

piperider_cli/profiler/profiler.py
Feature
To enhance the query performance
sc-28171
https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#threading-pooling-behavior
> To use a :memory: database in a multithreaded scenario, the same connection object must be shared among threads, since the database exists only within the scope of that connection.
None
=> [Feature] enhance column profiling performance by multithread

static_report/.gitignore, static_report/README.md
Dev Environment README (FE)
Fix out-of-date documentation
#392 
No
=> [Bug] readme (issue #392)

setup.py
Bug
The `date` type error of `snowflake-sqlalchemy` has been fixed from the upstream origin.
- https://github.com/InfuseAI/piperider/issues/305
- sc-27621
- https://github.com/snowflakedb/snowflake-sqlalchemy/issues/324
NONE
=> [Bug] Remove snowflake-sqlalchemy dependency

docs/metrics.md, piperider_cli/profiler/profiler.py, piperider_cli/profiler/schema.json
Feature
- extract table metadata from snowflake, bigquery, redshift
sc-28169
NONE
=> [Feature] extract metadata of cloud data warehouse

static_report/src/components/SingleReport/SRTableList/SRTableListColumnLabel.tsx
=> [Bug] apply label text max content

piperider_cli/compare_report.py, piperider_cli/runner.py
Chore
Compact `run.json` of `piperider run`
sc-28367
NONE
=> [Chore] Compact json of piperider run result

README.md, piperider_cli/datasource/duckdb.py, piperider_cli/datasource/survey.py, piperider_cli/error.py, piperider_cli/event/track.py, setup.py
Fix
- Update README
- Fix connector failed hint issue
sc-27803
=> [Feature] sc-27803 Add pip intstall piperider[csv] & piperider[parquet]

piperider_cli/datasource/duckdb.py, piperider_cli/error.py, piperider_cli/runner.py, setup.py
Bugfix
- Detect csv file encoding if create_engine failed due to file encoding is not UTF-8
- Provide suggest action for users to transfer file encoding format.
sc-28422
=> [Bug] sc-28422 detect csv file encoding and provide suggest ations

static_report/src/components/ComparisonReport/CRTableList/CRTableSchemaDetails.tsx, static_report/src/components/SingleReport/SRTableList/SRTableListSchemaDetail.tsx
**Single**
**Comparison**
https://user-images.githubusercontent.com/10325111/189021428-77fba00b-40c5-4dd2-b2c5-1c36486e11ca.mp4
- fixed schema text overflow
- fixed schema text overflow
- None
- None
=> [Bug] table schema overflow

piperider_cli/datasource/duckdb.py
Enhance
Enable duckdb `enable_progress_bar` flag to show progress bar when importing large files into in-memory db
sc-28513
=> [Feature] sc-28513 Show progress when loading large CSV or parquet file

piperider_cli/adapter/dbt_adapter.py, piperider_cli/cli.py, piperider_cli/datasource/__init__.py, piperider_cli/initializer.py
Chore
- remove skip dbt for an empty project
- change project name to datasource name
- accept underscore in datasource name
- no project init templates if users cancel init
sc-28292
NONE
=> [Chore] Enhance piperider init flow

docs/config.md, piperider_cli/__init__.py, piperider_cli/assertion_engine/recommender.py, piperider_cli/configuration.py, piperider_cli/error.py, piperider_cli/feedback.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, tests/profiler/test_profiler.py
feature
There would be plenty of tables in the data source.
However, not all the tables are necessary to profile.
e.g.,
1. Only a few key tables are interesting to profile
2. The table is a staging model in the transformation pipeline
3. It may take a long time to profile all the tables.
sc-28172
#401 
if `includes` is an empty array means no tables are included
```
includes: []
excludes: []
```
NONE
=> [Feature] Apply includes and excludes config to profiler

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/compare_report.py, piperider_cli/event/__init__.py, piperider_cli/event/track.py, piperider_cli/validator.py
Feature added
Support upload-report to the cloud
sc-28411
**Configuration**
In `~/.piperider/profile.yml` added:
```yaml
api_service: https://staging.cloud.piperider.io/
api_token: <the api token>
```
* api_service has default value: `https://cloud.piperider.io/`
* local dev: `https://127.0.0.1:3030/`
* staging: `https://staging.cloud.piperider.io/`
Get the token from the user dashboard:
**Commands**
* Add cloud section to `diagnose`
* A simple upload command
```
$ piperider upload-report --run /Users/qrtt1/temp/piperider/.piperider/aaaa/b/outputs/latest/run.json
{'filename': '9baa1ca4940c4c00b172588a543ee3b0.json', 'success': True}
```
=> [Feature] upload report command

piperider_cli/configuration.py
Fix error while running
https://docs.piperider.io/dbt-integration/quick-start-dbt-case
sc-28619
=> [Bug] In piperider init, merge the credential only in non-dbt project

README.md
Signed-off-by: Jens <47563038+jenswilms@users.noreply.github.com>
Update README
Better messaging related to Data profiling
=> [Document] Update readme data profiling

README.md
Signed-off-by: Liang-Bin Hsueh <hlb@infuseai.io>
=> [Document] Fix link for data sources on README

README.md
Signed-off-by: Jens <47563038+jenswilms@users.noreply.github.com>
=> [Document] Readme remove GIFS

piperider_cli/runner.py
feature
should not provide default descriptions in PipeRider
sc-28594
NONE
=> [Feature] Remove default value of descriptions

.github/workflows/flake8.yaml, docs/config.md, docs/metrics.md, piperider_cli/configuration.py, piperider_cli/profiler/profiler.py, piperider_cli/profiler/schema.json, piperider_cli/runner.py, tests/profiler/test_profiler.py, tests/test_builtin_assertions.py, tests/test_user_defined_assertions.py
feature
- new metrics: `duplicated_rows`, `samples`
- multi-thread table profiling
- docs for new metrics
sc-28170
#436 
NONE
=> [Feature] Add table duplicate rows profiling

piperider_cli/compare_report.py, piperider_cli/runner.py
bug
the symbolic link of the `latest` folder which links to the latest report folder should be a relative path
sc-28862
NONE
=> [Bug] Change symlink of latest folder of reports

README.md
Fix document
Fix the demo link from 0.7.0 to 0.9.0
n/a
=> [Chore] Update demo like from 0.7.0 to 0.9.0

README.md
Documentation revamp
Revise README to enable smoother onboarding and rework market positioning
At least get the readme to 80% point where it's good enough align with our next upcoming efforts (Q4+)
* This is a Work In Progress (WIP) - As roadmap and product direction is in the middle of transition, this PR is an interim update to sync those changes and map to our latest thoughts on the product. **So expect the core message to evolve as things are more clear. Let's keep focus on the 80% key message here, NOT PERFECTION**
* Refocus target audience of readme for DEVELOPERS ONLY (e.g. removed the persona section `For data eng, For data analyst`...)
* Made logo smaller, as …
=> [Document] : Readme Update (cleanup + product repositioning)

README.md
=> [Document] Update the sample report version to v0.10.0

piperider_cli/adapter/dbt_adapter.py, piperider_cli/error.py, piperider_cli/event/track.py
If executing dbt command with exit code=2, the return message cannot tell user what's going one
sc-29100
=> [Bug] Show corret error message if dbt invocation faield

piperider_cli/profiler/profiler.py, tests/profiler/test_profiler.py
bug
- fix wrong percentage calculation
- revise `duplicates` and `distinct` denominator 
sc-29132
NONE
=> [Bug] Fix wrong percentage calculation

piperider_cli/error.py, piperider_cli/event/track.py, piperider_cli/runner.py, piperider_cli/validator.py
bug
certain exceptions are not needed to send to Sentry
sc-28946
NONE
=> [Bug] Add filter of sending exception to sentry

piperider_cli/adapter/dbt_adapter.py, piperider_cli/assertion_engine/assertion.py, piperider_cli/profiler/schema.json, piperider_cli/runner.py, tests/runner/test_runner.py
feature
- move assertion results location in `run.json`
- flatten assertion results hierarchy
- add more properties to assertion result entry
sc-29029
NONE
=> [Feature] Refine assertion result entry and location

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/validator.py
Feature
- Refine CLI cloud login
- Refine CLI upload report with new API response
[![asciicast](https://asciinema.org/a/530370.svg)](https://asciinema.org/a/530370)
- Commands
- `piperider login`
Showing user profile information after login to piperider cloud by CLI
- `piperider login --token`
Use option `--token` to config API token directly without sending a magic link to user's email address
- `piperider login --enable-auto-upload/--disable-auto-upload`
Use enable/disable flags to control the default action of uploading report to cloud.
- `piperider run --upload`
Upload the report by flag `--upload` to cloud once the profiling report is generated, if …
=> [Feature] sc-29113 refine CLI cloud login & upload

piperider_cli/cloud_connector.py, piperider_cli/compare_report.py
bug
fix compare report interactive list due to assertion test results' structure and location modification
sc-29246
NONE
=> [Bug] Fix test count in compare reports list

piperider_cli/adapter/dbt_adapter.py, piperider_cli/profiler/schema.json, piperider_cli/runner.py, tests/runner/test_runner.py
feature
duplicate assertion test result location for backward compatible
sc-29029
NONE
=> [Feature] Duplicate assertion test result for backward compatible

piperider_cli/cloud_connector.py
Bugfix
Set Report URL field is no_wrap=true
sc-29296
=> [Chore] sc-29296 Report URL will be cut when terminal is not widthly

piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, setup.py
Feature
- Change to use MultipartEncoderMonitor to handle the callback of uploading report file 
sc-29234
=> [Feature] sc-29234 Show the correct progress bar when upload report

piperider_cli/__init__.py, piperider_cli/assertion_engine/assertion.py, piperider_cli/cli.py, piperider_cli/cloud_connector.py, piperider_cli/configuration.py, piperider_cli/datasource/__init__.py, piperider_cli/event/__init__.py, piperider_cli/initializer.py
Enhance UX
https://www.notion.so/infuseai/PipeRider-CLI-Config-Management-eebb112ff55e4e4ebbe24115fb014173
- `piperider config list-datasource`   : List current config
- `piperider config add-datasource`    : Add new datasource into current workspace
- `piperider config delete-datasource` : Delete datasource from current workspcae
n/a
=> [Feature] Config management subcommand

piperider_cli/cli.py
Chore
Mark cloud related command as beta feature
n/a
=> [Chore] Mark cloud releated commands as beta feature

piperider_cli/adapter/dbt_adapter.py, piperider_cli/runner.py
feature
Let table scan behavior be the same as non-dbt projects
sc-29291
NONE
=> [Feature] Remove dbt project default tables scan

piperider_cli/compare_report.py, tests/test_compare_report.py
feature
output compare summary in compare-reports to provide quick verifying information.
sc-29300
NONE
=> [Feature] output a comparison summary in the compare-reports command

piperider_cli/__init__.py
bug
not to show error message when initializing an empty project
sc-29385
NONE
=> [Bug] Fix showing error when init an empty project

piperider_cli/profiler/profiler.py
feature
`Float` type column may have `NaN`, `Infinity`, `-Infinity` special values
sc-29384
NONE
=> [Feature] Fix numeric column with NaN value

.github/workflows/ci-statics.yaml, static_report/src/components/shared/Columns/ColumnDetailMasterList/ColumnDetailListItem.tsx, static_report/src/components/shared/Columns/ColumnDetailMasterList/ColumnDetailMasterList.tsx, static_report/src/components/shared/Tables/TableColumnHeader.tsx, static_report/src/components/shared/Tables/TableList/TableColumnSchemaList.tsx, static_report/src/components/shared/Tables/TableOverview.tsx, static_report/src/components/shared/Widgets/ChartTabsWidget.tsx, static_report/src/components/shared/Widgets/DataCompositionWidget.tsx, static_report/src/components/shared/Widgets/DataSummaryWidget.tsx, static_report/src/components/shared/Widgets/QuantilesWidget.tsx, static_report/src/pages/CRColumnDetailsPage.tsx, static_report/src/pages/SRColumnDetailsPage.tsx, static_report/src/sdlc/single-report-schema.ts
Bugfix
Fix styling issues
N/A
**Does this PR introduce a user-facing change?**: Yes
* `?` icon on asymmetric columns fixed (CR)
* Url path for asymmetric columns fixed (CR)
* Grid alignment on composition metrics (CR)
=> [Bug] : metric styling: alignment, target>base fallback (column-details + missing icon / valids prog-bar)

piperider_cli/datasource/postgres.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py
bug
`NaN` checking should only apply on non-integer numeric column
sc-29384
NONE
=> [Bug] Fix NaN checking on numeric and non-integer column only

piperider_cli/runner.py
bug
After `v0.10.0`, the tables' profiling behavior changed and don't scroll automatically.
sc-29384
NONE
=> [Bug] Fix tables profiling progress bar scrolling behavior

piperider_cli/profiler/event.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, tests/profiler/test_profiler.py
=> [Feature] Change the way to fetch the table/column metadata

piperider_cli/profiler/profiler.py
Feature
Support multithread to fetch metadata
sc-29426
=> [Feature] Support multithread to fetch metadata

piperider_cli/compare_report.py, tests/test_compare_report.py
Enrich the summary outcome.
sc-29300
=> [Feature] Compare reports table summary refinement

piperider_cli/compare_report.py
feature
to show comparison summary markdown file path in CLI
sc-29300
NONE
=> [Feature] Add comparison summary report path notice

piperider_cli/cli.py, piperider_cli/compare_report.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py
feature
- add `--tables-from` option to compare reports command
- refine no tables selected behavior
sc-29587
NONE
=> [Feature] Add --tables-from flag for compare reports

piperider_cli/datasource/duckdb.py, piperider_cli/runner.py
feature
- add warning filter for duckdb reflection
- add default schema retrieve for duckdb
sc-29634
NONE
=> [Feature] Enhance DuckDB integration

piperider_cli/profiler/profiler.py
feature
- add UUID type column profiling
sc-29634
NONE
=> [Feature] Add UUID type column profiler

piperider_cli/datasource/bigquery.py, piperider_cli/runner.py
The `--dbt-state` does not work in bigquery
Bug
=> [Bug] Fix the dbt state problem for bigquery

piperider_cli/dbtutil.py, piperider_cli/profiler/profiler.py, piperider_cli/profiler/schema.json, piperider_cli/runner.py, static_report/src/components/shared/Assertions/AssertionCRModal.tsx, static_report/src/sdlc/single-report-schema.ts, tests/profiler/test_profiler.py, tests/test_dbt_util.py
Feature
Removal of legacy schema fields (tech debt)
29696
Compiled and with working shared components after removal: 
**Does this PR introduce a user-facing change?**: No
=> [Feature] : remove legacy assertion test + distribution schema signatures

static_report/package.json, static_report/src/components/Tables/TableList/TableColumnSchemaList.tsx
Fix
Fix for displayed `undefined` for comparison column name (when asymm.)
N/A
**Does this PR introduce a user-facing change?**: yes
fix issue where non-matching null column comparisons displayed `undefined`
=> [Bug] - lint script; string-casting bug (table-col-schema-list)

static_report/cypress/e2e/comparison-asym-base-target.cy.ts, static_report/cypress/e2e/comparison-report.cy.ts, static_report/cypress/e2e/single-report-abnormal-data.cy.ts, static_report/cypress/e2e/single-report.cy.ts, static_report/src/components/Assertions/AssertionCRModal.tsx, static_report/src/components/Charts/ChartContainer.tsx, static_report/src/components/Common/CommonModal.tsx, static_report/src/components/Common/Sidebar.tsx, static_report/src/components/Tables/TableList/TableColumnSchemaList.tsx, static_report/src/components/Tables/TableList/TableListItem.tsx, static_report/src/components/Tables/TableList/TableListItemDecorations.tsx, static_report/src/pages/CRColumnDetailsPage.tsx, static_report/src/pages/CRTablesListPage.tsx, static_report/src/pages/SRColumnDetailsPage.tsx, static_report/src/pages/SRTablesListPage.tsx, static_report/src/utils/layout.ts
**Single**
https://user-images.githubusercontent.com/10325111/207200134-69af5d2d-48d9-40bf-993a-fcc4c87f90a6.mp4
**Comparison**
https://user-images.githubusercontent.com/10325111/207200179-ad3a5980-79a0-4cba-8707-d17dfebae00d.mp4
=> [Chore] refactor report list to apply new ui

static_report/src/pages/CRTablesListPage.tsx, static_report/src/pages/SRTablesListPage.tsx
=> [Chore] add the table description

piperider_cli/dbtutil.py, piperider_cli/profiler/__init__.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, tests/profiler/test_profiler.py, tests/test_dbt_util.py
feature
- add profile subject
- revise metadata fetch procedure
- revise dbt utility behavior
sc-29860
NONE
=> [Feature] Support custom schema for dbt state integration

static_report/src/pages/CRColumnDetailsPage.tsx, static_report/src/pages/SRColumnDetailsPage.tsx
Fix
N/A
Fix issue with navigating the new UI dropdown in the data sidebar
=> [Bug] : incorrect url path when changing table dropdown

piperider_cli/configuration.py, piperider_cli/dbtutil.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, tests/test_dbt_util.py
feature
- support view profiling configuration
- apply inclusion and exclusion to dbt state candidates
sc-29862
NONE
=> [Feature] Support view profiling

static_report/src/utils/theme.ts
https://user-images.githubusercontent.com/10325111/209033068-04e26e8b-76e8-42df-9959-6f7b53ffe188.mp4
=> [Chore] add piperider variant button

piperider_cli/profiler/profiler.py
=> [Feature] Support bigquery array

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py
feature
- add a new cloud comparison reports command
- need to specify `--base` and `--target` report
- use `--summary` to store the summary markdown file
sc-29771
NONE
=> [Feature] Generate comparison summary on cloud

piperider_cli/runner.py
feature
-  keep track of the dbt state along with the piperider run report
sc-30099
NONE
=> [Feature] Copy dbt state files to the report folder

piperider_cli/cli.py, piperider_cli/cloud_connector.py
chore
- explain more `piperider cloud compare-reports` input usage
- show the generated comparison report URL
sc-29771
NONE
=> [Chore] Add command description and generated url path

piperider_cli/dbtutil.py, piperider_cli/metrics_engine/__init__.py, piperider_cli/metrics_engine/event.py, piperider_cli/metrics_engine/metrics.py, piperider_cli/profiler/schema.json, piperider_cli/runner.py
feature
- support dbt metric query with time grain
sc-30090
NONE
=> [Feature] Support dbt metric query

piperider_cli/profiler/profiler.py
Signed-off-by: David Johnson <dajohnson@purestorage.com>
Fix for an open issue that I also hit
This prevents overflows when calculating stddev
https://github.com/InfuseAI/piperider/issues/541
None
=> [Bug] issues:541 fix overflow issue

piperider_cli/datasource/__init__.py, piperider_cli/runner.py, piperider_cli/validator.py
issue: 558
Signed-off-by: David Johnson <dajohnson@purestorage.com>
Bug fix
Allow validating to pass when using `include_views=True' and a db only has views
issue: 558
None
=> [Bug] Validate with views as well as tables(if applicable)

piperider_cli/metrics_engine/metrics.py
bug
- fix aggregation function naming
- use literal column column for column expression
- fix start date limitation
sc-30090
NONE
=> [Bug] Fix business metric query statement

static_report/src/components/Charts/BMBarChart.tsx, static_report/src/components/Charts/BMLineChart.tsx
=> [Chore] : use Array.from notation instead of spread of Map iterables

piperider_cli/dbtutil.py
bug
- skip business metric querying if metric with the window property
sc-30090
NONE
=> [Bug] Skip querying dbt metrics with the window property

piperider_cli/compare_report.py
feature
- provide business metric comparison in the comparison summary
sc-30232
NONE
=> [Feature] Support business metric comparison in the comparison summary

piperider_cli/metrics_engine/metrics.py
Bug fix
- fix date utility function compatibility for bigquery, duckdb, postgresql
sc-30339
NONE
=> [Bug] dataadd not working in duckdb

piperider_cli/cli.py
feature
- make `piperider cloud` and `piperider config` command visible
- remove beta message in `piperider cloud` and `piperider config` command manual
sc-30162
NONE
=> [Feature] Make cloud and config command visible and remove beta message

piperider_cli/metrics_engine/metrics.py
feature
If there is no metric result in a certain query period, the query result is NULL.
And if the metric is based on the calculation method count, count_distinct, and sum, then changing null to zero is more reasonable.
sc-30381
NONE
=> [Feature] Append zero when a count metric or a sum metric result is null

piperider_cli/metrics_engine/metrics.py
feature
- append zero to derived metrics that have zero value
- deal with the *Division by zero* problem when derived metrics have division expression
sc-30381
NONE
=> [Feature] Append zero if derived metrics had null value

piperider_cli/datasource/__init__.py, piperider_cli/datasource/bigquery.py, piperider_cli/datasource/duckdb.py, piperider_cli/datasource/postgres.py, piperider_cli/datasource/redshift.py, piperider_cli/datasource/snowflake.py, piperider_cli/datasource/sqlite.py, piperider_cli/dbtutil.py, piperider_cli/metrics_engine/metrics.py, piperider_cli/profiler/event.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, setup.py, tests/common.py, tests/profiler/test_multi_db.py, tests/profiler/test_profiler.py, tests/test_dbt_util.py
resolve #556
If a dbt model uses custom databases, we now support to profile this model rather than skipping it.
Feature
#556 sc-30334
=> [Feature] support dbt with multiple databases

piperider_cli/datasource/bigquery.py
=> [Bug] Fix bigquery to_database_url() param name

piperider_cli/datasource/__init__.py, piperider_cli/runner.py, piperider_cli/validator.py
feature
- due to custom schema, we shouldn't verify connection by tables reflection
sc-30390
NONE
=> [Feature] Verify connection without table reflection

piperider_cli/metrics_engine/metrics.py
feature
- cast timestamp column of metrics is possible to date type explicitly.
sc-30389
NONE
=> [Feature] Cast timestamp column of metrics to date type

piperider_cli/dbtutil.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, tests/profiler/test_profiler.py, tests/test_dbt_util.py, tests/test_runner.py
Refactory. Make all filter logic to central place.
chore
- refactor getting subjects to be profiled behavior
- make the profiler a pure library
sc-30390
NONE
=> [Chore] Move the table filter logic from profiler to runner

piperider_cli/runner.py
bug
- progress bar column width error when there's no available profile subjects.
sc-30426
NONE
=> [Bug] Return zero length for column width of progress bar when no subjects

README.md
Signed-off-by: Jens <47563038+jenswilms@users.noreply.github.com>
=> [Document] Update ReadMe

piperider_cli/configuration.py, piperider_cli/datasource/__init__.py, piperider_cli/datasource/bigquery.py, piperider_cli/datasource/duckdb.py, piperider_cli/datasource/postgres.py, piperider_cli/datasource/redshift.py, piperider_cli/datasource/snowflake.py, piperider_cli/datasource/sqlite.py, piperider_cli/initializer.py, piperider_cli/runner.py, piperider_cli/validator.py
feature
- add global dbt configuration
- revise piperider init and default datasource behavior
- revise config add/delete/list behavior
sc-30430
#578 
NONE
=> [Feature] Implicit data sources from dbt profile target

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/validator.py
Feature
- Add comments `piperider cloud list-projects` and `piperider cloud select-project`
- List-projects
- Select-project
- Upload report with a specific project
- Show the default project in diagnose command
- The default project setting will be stored in `~/.piperider/profile.yml`
sc-30066
=> [Feature] sc-30066 Support mutiple projects

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/compare_report.py
Enhancement
- If no base or target provides when calling `cloud compare-reports` command, will use the report selector to select uploaded reports from the cloud
n/a
=> [Feature] Cloud compare-reports command support selector

piperider_cli/datasource/__init__.py
bug
- in sqlalchemy 1.3, column argument should be a list type in `select()`
sc-30457
NONE
=> [Bug] Fix column argument in select function of sqlalchemy 1.3

piperider_cli/metrics_engine/metrics.py
Bug
If the table name contains hyphen. (e.g. `table-name`) there would be query error.
=> [Bug] Fix metric query issue in bigquery

piperider_cli/cli.py, piperider_cli/configuration.py, piperider_cli/dbtutil.py, piperider_cli/runner.py, tests/test_dbt_util.py
feature
- separate `dbt-state` and `dbt-run-results`
- annotate models as piperider profiling candidate
sc-30431
#578
In a dbt project, `piperider run` associates dbt state as default behavior.
=> [Feature] Associate dbt state and dbt run result for piperider run

piperider_cli/datasource/__init__.py, piperider_cli/metrics_engine/metrics.py, piperider_cli/profiler/event.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py
1. Support threads in [dbt profile](https://docs.getdbt.com/docs/get-started/connection-profiles#setting-up-your-profile)
2. Put back the fetching metadata as the first step of profiling
3. Add asyncio to manage the flow in profiler and metric engine
4. Table metadata (rows, duplicated rows, volume size) and columns profiling now can run concurrently at the same time
Feature
=> [Feature] Enhance the multi thread behavior

piperider_cli/cli.py, piperider_cli/dbtutil.py, piperider_cli/runner.py, tests/mock_dbt_data/manifest.json, tests/test_dbt_util.py
feature
- pipe `dbt list` to piperider run as stdin input
#578 
sc-30432
NONE
=> [Feature] Associate dbt list pipe in models and metrics

piperider_cli/datasource/__init__.py, piperider_cli/datasource/bigquery.py, piperider_cli/datasource/duckdb.py, piperider_cli/datasource/postgres.py, piperider_cli/datasource/redshift.py, piperider_cli/datasource/snowflake.py, piperider_cli/datasource/sqlite.py, piperider_cli/runner.py
feature
- dbt manifest's and piperider config datasource target may not be the same
#578 
sc-30466
NONE
=> [Feature] Check dbt manifest compatible with the data source dbt target

static_report/src/components/Columns/MasterSideNav/MasterSideNav.tsx, static_report/src/components/Columns/MasterSideNav/TableItemAccordionButton.tsx, static_report/src/components/Common/MasterDetailContainer.tsx, static_report/src/components/Reports/ReportContextBar.tsx, static_report/src/components/Widgets/DataCompositionWidget.tsx, static_report/src/pages/CRAssertionListPage.tsx, static_report/src/pages/CRBMPage.tsx, static_report/src/pages/CRProfileRunPage.tsx, static_report/src/pages/CRTableListPage.tsx, static_report/src/pages/SRAssertionListPage.tsx, static_report/src/pages/SRBMPage.tsx, static_report/src/pages/SRProfileRunPage.tsx, static_report/src/pages/SRTablesListPage.tsx, static_report/src/utils/layout.ts
enhancement/fix
fixes inconsistent layout scrolling and padding implementations
N/A
- This PR centralizes all padding/scroll behavior at the `MasterDetailContainer`
- Adds a visible marker for the accordion toggle of `MasterSideNav`
**Does this PR introduce a user-facing change?**: Yes
Improved visibility of accordion toggle. Fixed inconsistent scroll behaviors on certain pages
=> [Feature] - UI v3 adjustments (sidebar toggle, layout scrolling)

piperider_cli/initializer.py
Bug fix
- Fix init fail issue when generate default recipe
sc-30452
=> [Bug] init error when generate recipe

piperider_cli/recipes/__init__.py, piperider_cli/recipes/utils.py
Bug fix
- Switch back to the current git branch all the time
- Remove timeout when execute the compare recipe
sc-30547
=> [Bug] sc-30547 Switch back to current branch when command fail

piperider_cli/recipes/default_recipe_generator.py
Feature
- Show the recipe file path when init the default recipe
sc-30544
=> [Chore] sc-30544 Show the recipe file path

piperider_cli/event/__init__.py
feature
- to add additional attributes of command events.
sc-30460
NONE
=> [Feature] Track piperider command upload and share event

piperider_cli/cli.py, piperider_cli/configuration.py, piperider_cli/dbtutil.py, piperider_cli/runner.py, tests/test_dbt_util.py, tests/test_runner.py
feature
- add the explicit option, --dbt-list to specify there's dbt list stdin
- add mutually exclusive check for options
- raise profiling priority of tag higher than piperider configuration
- refactor dbt integration part
sc-30543
NONE
=> [Feature] Change profile tag precedence

README.md
=> [Document] Update the example report

.github/workflows/pypi.yaml
chore
- update example reports repo
sc-30422
NONE
=> [Chore] Update example reports repo

static_report/src/components/Reports/ReportContextBar.tsx
=> [Chore] : report-context-bar (action-slot)

piperider_cli/recipes/utils.py
Bugfix
Handle the edge when git is not installed
sc-30557
=> [Bug] sc-30557 Handle edge case when git is not installed

piperider_cli/recipes/__init__.py
Bugfix
- Don't check dbt command if recipe file don't have dbt
sc-30557
=> [Bug] sc-30557 if dbt commands is not assigned, skip dbt env check

piperider_cli/datasource/duckdb.py
Bugfix
Fix compatibility with duckdb 0.7.x. duckdb 0.6.x returns `main` as database, but 0.7.x returns filename as database
=> [Bug] Compatible with duckdb 0.7.x while checking dbt manifest compatibility

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py
feature
- refine `piperider cloud login` flow
sc-30494
=> [Feature] Refine signup signin flow for cli 

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/compare_report.py, piperider_cli/recipe_executor.py, piperider_cli/recipes/__init__.py
Feature
- Implement `--upload` and `--share` options for compare command
- Command `piperider compare-reports` also support `--upload` and `--share` options
=> [Feature] sc-30488 Implement --upload and --share options for compare

piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py
feature added
apply the changes from the API server
sc-30495
=> [Feature] Rename organization to workspace

static_report/src/App.tsx, static_report/src/utils/amplitudeEvents.ts
Bugfix
To know users' context to improve our product usability
sc-30597
=> [Bug] Add tracking-event for mobile-device warning

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/compare_report.py, piperider_cli/datasource/__init__.py, piperider_cli/profiler/schema.json
- Support new workspace logic
Fix
- Change the output of list-projects and select-project with new workspace design
sc-30645
=> [Feature] sc-30645 Update select-project and list-projects command

piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py
Enhancement
Migration API to v2
sc-30649
=> [Feature] Upgrade to api v2

piperider_cli/recipes/__init__.py, piperider_cli/recipes/utils.py
Feature
- Base recipe will checkout to merge-base if the base branch is provided.
sc-30599
=> [Feature] Will checkout to merge-base if base branch provided

piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/compare_report.py, piperider_cli/error.py
The sharing url changes to the same as original report url
Feature
sc-30593
=> [Feature] The sharing url changes to the same as original report url

static_report/src/pages/CRPage.tsx
=> [Chore] Add SSR for CRPage

static_report/src/components/Columns/MasterSideNav/MasterSideNav.tsx, static_report/src/components/Columns/MasterSideNav/TableItemAccordionButton.tsx
=> [Chore] Fix typescript type error

Dockerfile, Makefile
Chore
- Change the docker hub repository from `infuseai/piperider` to `piperider/piperider`
sc-30877
=> [Chore] Change the dockerhub repository for storing docker image

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/event/__init__.py, piperider_cli/recipes/github_action.py, piperider_cli/recipes/utils.py
feature
Add helper to github action
sc-30601
=> [Feature] github action helper

piperider_cli/recipes/github_action.py
Featrue
- Enhance the functions for github action
sc-30601
=> [Feature] sc-30601 Enhance the functions for github action

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/compare_report.py
feature
- To unify command options of `run`, `compare-reports`, `compare`
- sc-30602
NONE
=> [Feature] Unify command options for run and compare

piperider_cli/recipe_executor.py
> UnboundLocalError
> local variable 'dbt_project_path' referenced before assignment
=> [Chore] Fix dbt project path

static_report/src/App.tsx, static_report/src/components/Common/Main.tsx, static_report/src/components/Common/MasterDetailContainer.tsx, static_report/src/components/Common/Navbar.tsx, static_report/src/components/Reports/ReportContextBar.tsx, static_report/src/pages/CRPage.tsx, static_report/src/pages/SRColumnDetailPage.tsx, static_report/src/pages/SRPage.tsx
=> [Chore] Adjust the logo size

piperider_cli/__init__.py, piperider_cli/assertion_generator.py, piperider_cli/cloud_connector.py, piperider_cli/compare_report.py, piperider_cli/generate_report.py, piperider_cli/runner.py
bug
on windows, users need the admin privilege to create symlink.
sc-30374
NONE
=> [Bug] Fix symlink privilege issue from windows

piperider_cli/recipes/__init__.py
Enhancement
Convert the exception to warnings only.
sc-30887
=> [Chore] Show warnings when external piperider executor failed

piperider_cli/event/track.py
enhancement
1. warning users when the STDIN is not available
2. ignore the exception (don't send it to log service)
sc-30887
**for Reviewer Notes**
We can reproduce it by running a container without TTY (`-it`)
```
$ docker run --rm pp-lab1 piperider init
Initialize piperider to path /app/.piperider
[?] What is your data source name? (alphanumeric and underscore are allowed): Error: EOF when reading a line
Error: The 'init' command could not be executed due to the unavailability of STDIN, which is required to receive user input.
```
=> [Chore] Warning when stdin not available

piperider_cli/cloud_connector.py, piperider_cli/datasource/__init__.py, piperider_cli/datasource/field.py, piperider_cli/event/track.py
bugfix
* add hints for users to add options to pick up a project
sc-30887
example from github action:
=> [Bug] Show messages while stdin no available at cloud-login action

.github/workflows/tests.yaml, piperider_cli/assertion_engine/types/assert_column_misc.py, piperider_cli/datasource/__init__.py, piperider_cli/datasource/duckdb.py, piperider_cli/datasource/sqlite.py, piperider_cli/metrics_engine/metrics.py, piperider_cli/profiler/profiler.py, setup.py, tests/profiler/test_profiler.py
Support latest [sqlalchemy 2.0](https://www.sqlalchemy.org/blog/2023/01/26/sqlalchemy-2.0.0-released/)
Feature
sc-30411
=> [Feature] support sqlalchemy 2 0

piperider_cli/datasource/__init__.py, piperider_cli/datasource/athena.py, piperider_cli/metrics_engine/metrics.py, piperider_cli/profiler/profiler.py, setup.py
Resolve #452
Support athena. Use the profile configuration defined by https://github.com/dbt-athena/dbt-athena
Feature
sc-30879
=> [Feature] Support AWS Athena

piperider_cli/dbtutil.py, piperider_cli/runner.py, piperider_cli/statistics.py, tests/test_runner.py
feature
show filter logic to be more informative
sc-30464
NONE
=> [Feature]  Show filter logic for profiling and metric queries

piperider_cli/cli.py
Chore / enhancement
Receive return code from uploading report
=> [Chore] Receive return code from uploading report

piperider_cli/__init__.py, piperider_cli/cli.py, piperider_cli/dbtutil.py, piperider_cli/recipe_executor.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/recipe_schema.json
feature
- support specified run report and jinja format for piperider compare with recipe
sc-30548
NONE
=> [Feature] Support file and jinja format for compare recipe

piperider_cli/dbtutil.py
bug
dbt allows to use jinja format in `dbt_project.yml`, therefore piperider needs to support it.
sc-31083
NONE
=> [Bug] Support reading jinja format in dbt project yaml

static_report/src/components/Charts/utils.tsx, static_report/src/components/Widgets/ChartTabsWidget.tsx, static_report/src/pages/CRColumnDetailPage.tsx, static_report/src/pages/CRTableDetailPage.tsx, static_report/src/pages/SRColumnDetailPage.tsx, static_report/src/sdlc/single-report-schema.ts
1. Show the missing column/table as blank block
2. Base/Target both show the title
=> [Feature] Show empty block for missing table/column in the report

piperider_cli/__init__.py, piperider_cli/dbtutil.py
bug
The initial `dbt_project.yml` has a one-line comment in jinja format.
there's potential problems if we render jinja format then read yaml content.
bug
NONE
=> [Bug] Load dbt project yaml then render jinja format

piperider_cli/dbtutil.py
bug
- to reduce the compatibility issue
sc-31184
#665 
NONE
=> [Bug] Load the dbt project fields that piperider needs

piperider_cli/cloud_connector.py
bug
- provide a friendly view for users to click and copy and uploaded reports' url
sc-31109
NONE
=> [Bug] Adjust console view of uploaded reports

piperider_cli/profiler/profiler.py, piperider_cli/profiler/schema.json, piperider_cli/runner.py, static_report/src/components/Charts/utils.tsx, static_report/src/components/Widgets/ChartTabsWidget.tsx, static_report/src/sdlc/single-report-schema.ts
bug
- prevent from histogram profiling failing due to having infinite values in `float` column
sc-30933
NONE
=> [Bug] Fix profiler failing when infinite values are given

piperider_cli/profiler/profiler.py, piperider_cli/runner.py
Bugfix
- Fix command `piperider run --table xxx` will get the wrong schema if the schema setting in dbt profile is not the default schema
GitHub: #666 
Shortcut: sc-31212
=> [Bug] sc-31212 Fix piperider run --table get wrong schema issue

piperider_cli/cli.py, piperider_cli/dbtutil.py, piperider_cli/guide.py, piperider_cli/initializer.py, piperider_cli/recipes/default_recipe_generator.py, piperider_cli/runner.py
=> [Feature] sc-31163 PipeRider run & compare can be executed without init 

static_report/src/components/Columns/MasterSideNav/MasterSideNav.tsx, static_report/src/components/Common/HelpMenu.tsx, static_report/src/components/Common/Main.tsx, static_report/src/components/Reports/ReportContextBar.tsx, static_report/src/pages/CRAssertionListPage.tsx, static_report/src/pages/SRAssertionListPage.tsx, static_report/src/utils/store.ts
Bugfix
- Set z-index of ReportContextBar
- Assertion button only remove when not base and target asserions
- Feedback Link support both local report and cloud env
sc-31205
=> [Bug] Fix some frontend issues

static_report/src/components/Common/Navbar.tsx
Bugfix
- Fix help menu zIndex issue
N/A
=> [Bug] fix help menu zindex issue

setup.py
bug
- duckdb-engine v0.7.1 release and it fix compatibility issue with sqlalchemy
sc-31203
NONE
=> [Bug] Remove sqlalchemy restriction

piperider_cli/dbtutil.py, piperider_cli/generate_report.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, tests/test_dbt_util.py, tests/test_runner.py
enhancement
* scan all schema in the dbt project to trace changes
sc-31196
**Special notes for your reviewer:**
*DONT MERGE IT BEFORE `0.25.0`*
We have updated the Piperider profiling behavior to integrate it with the DBT project. Previously, the profiling was a one-time scan of models with tags, including metadata fetching and execution profiling.
Now, in the new version, we have separated the metadata collection and profiling into two distinct phases:
1. Piperider will gather all metadata to track schema changes for models, seeds, and sources.
2. Piperider will continue to profile only those models that have been tagged …
=> [Feature] Track schema changes in the dbt project

piperider_cli/cli.py, piperider_cli/generate_report.py, piperider_cli/profiler/profiler.py, piperider_cli/runner.py, piperider_cli/statistics.py
=> [Chore] Modify the piperider run output wording

static_report/src/components/Tables/TableList/TableListItem.tsx, static_report/src/pages/CRTableListPage.tsx, static_report/src/pages/SRTablesListPage.tsx
The table list in the new report show wrong tables. It should not include tests
=> [Bug] Fix the table list show wrong table entries

piperider_cli/compare_report.py, piperider_cli/generate_report.py
bug
- long report location may be wrapped and cannot be clicked directly
sc-31470
NONE
=> [Bug] Add soft wrap to console print for report location

static_report/src/components/LineageGraph/GraphNode.tsx, static_report/src/components/LineageGraph/ReactFlowGraph.tsx
PoC
- When the mouse moves into a node, highlight all the related edges and
nodes depended by the selected node
=> [Chore] lineage graph w22 highlight selected path

piperider_cli/cli.py, piperider_cli/recipe_executor.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/default_recipe_generator.py, piperider_cli/recipes/github_action.py, piperider_cli/recipes/utils.py
enhancement
Enable the `--dry-run` and `--interactive` options to allow users to observe the actions performed by the recipes without actually executing them.
sc-31096
----
https://www.loom.com/share/9802c33dd8ff4fab8d05c2bddebb9340
https://www.loom.com/share/1a7123fbbac3477e900658ad8affe79f
=> [Feature] piperider compare improvement

piperider_cli/runner.py
Bug
- Due to we will show dbt test results by default, and the assertion will be deprecated in the future. The dbt test results should not affect the return code of the piperider run.
sc-31540
=> [Bug] sc-31540 The dbt test result will not effect return code

piperider_cli/assertion_engine/recommended_rules/table_assertions.py
Check if the stats is available or the assertions would not be generated.
=> [Bug] generate-assertions always fail because the table is not always profiled

piperider_cli/cli.py, piperider_cli/configuration.py, piperider_cli/error.py
Bugfix
- Modify the error and hint message when no config file is found.
- Show the URL to the doc site and ask users to follow the quick start to setup the piperider project.
sc-31552
=> [Bug] sc-31552 Modify the error and hint message when no config file

piperider_cli/recipes/github_action.py
chore
- update piperider action helper function to fit piperider init-less 
sc-31504
NONE
=> [Chore] Adjust prepare for action for init-less piperider

piperider_cli/cli.py, piperider_cli/compare_report.py, piperider_cli/dbtutil.py, piperider_cli/recipes/__init__.py
Feature
Compare command now will apply tags in the target branch to base branch
sc-31492
for internal review:
https://www.loom.com/share/bcf6cfb10aeb49e8ad24f151575ae180
https://www.loom.com/share/a01a69dd4acf4d18a1d5c822bd3e05dc
=> [Feature] Profile models based on tags in the target branch

piperider_cli/recipes/__init__.py
bugfix
Fix missing method
```py
Configuration.load()
```
should be
```py
Configuration.instance()
```
=> [Bug] Fix configuration loading

piperider_cli/event/__init__.py, piperider_cli/event/collector.py, piperider_cli/initializer.py, piperider_cli/recipe_executor.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/default_recipe_generator.py
feature
- Because we introduce init-less feature, we could simplify our piperider metadata.
- remove `.unsend_events.json
- generate default recipe on the fly
sc-31503
NONE
=> [Feature] Move .unsend_events and generate default recipe on the fly

piperider_cli/cli.py, piperider_cli/guide.py
bug
- when enabling `auto-upload`, it would strictly check whether user login status and throw exception.
sc-31625
NONE
=> [Bug] Add warning to auto-upload when not login instead of exception

piperider_cli/dbt/list_task.py, tests/test_dbt_integeration.py
=> [Bug] make list-task working both dbt 1.4 and 1.5

static_report/src/components/LineageGraph/graph.ts
=> [Chore] Fix lint from lineage graph

piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/error.py
Show error message if generating comparison report failed instead of silent fail.
=> [Bug] Show error message if generate comparison in the cloud failed

piperider_cli/assertion_engine/assertion.py, piperider_cli/cli.py, piperider_cli/configuration.py, piperider_cli/datasource/duckdb.py, piperider_cli/datasource/sqlite.py, piperider_cli/dbtutil.py, piperider_cli/guide.py, piperider_cli/initializer.py, piperider_cli/recipe_executor.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/default_recipe_generator.py, piperider_cli/recipes/utils.py, piperider_cli/runner.py, piperider_cli/validator.py, tests/test_user_defined_assertions.py
Feature
- Change the dbt project search logic. We will search dbt project from the parent path instead of searching sub folders.
- We also search piperider project folder from the parent path. All the commands support this change.
sc-31557
No
=> [Feature] Allows to run piperider in the sub folder

piperider_cli/__init__.py, piperider_cli/event/collector.py, piperider_cli/reports/__init__.py
bug
- There is a text limit to the comment that get published to Github actions.
sc-31614
#732 
NONE
=> [Bug] Comparison summary content length control

piperider_cli/dbtutil.py
Bugfix
Fix the wrong metric unique id from target branch
=> [Bug] Fix the wrong metric unique id from target branch

.github/workflows/tests.yaml
Infrastructure
- Integrate PipeRider test with codecov
N/A
N/A
N/A
=> [Chore] Integrate test action with codecov

README.md
Infrastructure
- Add codecov badge into README.md
N/A
N/A
N/A
=> [Chore] Add codecov badge into README.md

static_report/src/components/LineageGraph/GraphNode.tsx, static_report/src/components/LineageGraph/LineageGraph.tsx, static_report/src/components/LineageGraph/graph.ts, static_report/src/components/Widgets/BMWidget.tsx
1. Fix the metric range problem
2. Add tooltip on resource icon and change icon
3. Show information that it's change only view
4. Fix the border style for changed metric
5. The change only in lineage graph would include all downstreams
=> [Bug] Fix metric date range display

piperider_cli/cli.py, piperider_cli/cloud/__init__.py, piperider_cli/configuration.py
feature
- move cloud configuration from global to per local project
sc-31236
NONE
=> [Feature] Add cloud config to local project config

static_report/src/pages/CRBMPage.tsx, static_report/src/pages/SRBMPage.tsx, static_report/src/utils/dbt.ts, static_report/src/utils/store.ts
1. Build the metric tree in the sidebar hierarchy
2. Update the metric detail page
=> [Feature] Add metric hierarchy in the sidebar menu

piperider_cli/compare_report.py, piperider_cli/dbt/list_task.py, piperider_cli/dbtutil.py, piperider_cli/generate_report.py, piperider_cli/metrics_engine/metrics.py, piperider_cli/profiler/profiler.py, piperider_cli/profiler/schema.json, piperider_cli/reports/__init__.py, piperider_cli/runner.py, static_report/src/sdlc/schema-meta.ts, static_report/src/sdlc/single-report-schema.ts, static_report/src/types/index.ts, static_report/src/utils/dbt.ts, static_report/src/utils/store.ts, tests/mock_dbt_data/sc-31587-base.json, tests/mock_dbt_data/sc-31587-input.json, tests/mock_dbt_data/sc-31587-with-ref-base.json, tests/mock_dbt_data/sc-31587-with-ref-input.json, tests/test_dbt_integeration.py
feature
behavior changes for list explicit and implicit 
sc-31587
=> [Feature] update explicit and implicit changes 

tests/datasource/test_datasource.py, tests/datasource/test_duckdb.py
Unit Test
- Add Unit Test for data source and DuckDB
N/A
N/A
N/A
=> [Chore] Add unittest for datasource

piperider_cli/dbt/list_task.py
bugfix
The newer dbt requires the `project_target_path` arguments
none
=> [Bug] Fix required project's target path

static_report/src/components/Icons/index.tsx, static_report/src/components/LineageGraph/GraphNode.tsx, static_report/src/components/SideBar/SideBarTree.tsx
=> [Chore] Add implicit icon

static_report/src/sdlc/core.js, static_report/src/utils/dbt.ts
Use the implicit change set in the comparison report.
=> [Feature] Add the implicit change to the metric tree

piperider_cli/configuration.py, piperider_cli/initializer.py, piperider_cli/validator.py
feature
- need a mechanism to infer project when no reports exist
sc-31747
NONE
=> [Feature] Add project id inference mechanism

piperider_cli/recipes/__init__.py
bugfix
Make the recipe tolerations for `command`
sc-31600
=> [Bug] Handle the edge case for command-list in command field

piperider_cli/profiler/profiler.py
bugfix
handle the edge case for fetching metadata
sc-31724
=> [Bug] Handle no-such-table error when the metadata is not available

piperider_cli/dbt/list_task.py
bug
- fix warning when calculating implicit changeset 
sc-31760
NONE
=> [Bug] Fix compare reports with metrics not queried

piperider_cli/configuration.py, piperider_cli/datasource/duckdb.py, piperider_cli/dbtutil.py, piperider_cli/error.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/utils.py
Feature
1. With git-archive, the untracked files are allowed
2. No need to switch branches
sc-31292
for internal:
https://www.loom.com/share/9dda38174ed54818926dc7c65b4267f3
=> [Feature] Support git archive in piperider compare

.github/workflows/dbt-compatible-tests.yaml, piperider_cli/cli.py, piperider_cli/configuration.py, piperider_cli/dbt/list_task.py, piperider_cli/dbtutil.py, piperider_cli/error.py, piperider_cli/runner.py, tests/mock_dbt_project/dbt_project.yml, tests/mock_dbt_project/profiles.yml, tests/test_dbt_util.py
Feature
- Rename run command option `--dbt-state` to `--dbt-target-path`
- Add run command option `--state` to select compare target path
- Run command support to use `--select state:modified+ --state <path-to-compare-target>`
https://www.loom.com/share/b4c3365db5984b6eadc9be20480f4ba2?sid=188d87e4-f764-4bda-8961-3812afa99514
sc-31688
=> [Feature] sc-31688 PipeRider run support `--select state:modified+`

static_report/src/components/LineageGraph/graph.ts
The change only does not work correctly.
=> Fix the change status in lineage graph issue

piperider_cli/compare_report.py, piperider_cli/dbt/changeset.py
Make the `summary-aggregate` taking responsibility to calculate all changes
=> [Chore] Refactoring ChangeSet

piperider_cli/cli.py
=> [Chore] Fix typo

static_report/src/components/Overview/Overview.tsx
=> [Bug] Fix the search not working in single report

.github/workflows/dbt-compatible-tests.yaml, piperider_cli/dbt/changeset.py, piperider_cli/dbt/utils.py
bug
- display change color show opposite meaning
sc-31723
NONE
=> [Bug] Add changesets member check and adjust color display

static_report/src/components/Overview/Overview.tsx
=> [Chore] Fix type checking error in cloud

static_report/src/App.tsx, static_report/src/components/LineageGraph/LineageGraph.tsx, static_report/src/components/LineageGraph/graph.ts, static_report/src/components/SideBar/SideBar.tsx, static_report/src/hooks/useHashLcocation.ts, static_report/src/utils/routes.ts
1. Add mechanism to read the search params from the hash path
2. Support permalink for graph display, stat, filter_by
Feature
- Read URL query params from anchor hash
sc-31835, sc-31798
=> [Feature] Read URL query params from anchor hash

piperider_cli/recipes/__init__.py
Bugfix
- The base branch should be merge_base(base_branch, 'HEAD')
sc-31852
=> [Bug] sc-31852 compare should use merge-base result for base phase

static_report/src/components/Common/Navbar.tsx, static_report/src/components/Overview/ChangeSummary.tsx, static_report/src/components/Overview/Overview.tsx, static_report/src/components/SideBar/SideBar.tsx
=> [Feature] lineage graph button in the overview and sidebar

piperider_cli/datasource/__init__.py, piperider_cli/datasource/databricks.py, piperider_cli/metrics_engine/metrics.py, setup.py
Feature
Support databricks data source
sc-31809
=> [Feature] sc-31809 Init the datasource class for databricks

README.md
Chore
- Update README.md
sc-31871
=> [Chore] sc-31871 update the URL of pricing page

piperider_cli/recipes/github_action.py
Bugfix
Fix PipeRider Compare Action failed issue
sc-31777
=> [Bug] sc-31777 Fix compare action failed issue

piperider_cli/profiler/schema.json, piperider_cli/recipes/__init__.py, piperider_cli/runner.py, static_report/src/components/Common/Main.tsx, static_report/src/components/Overview/Overview.tsx, static_report/src/components/Reports/ReportContextBar.tsx, static_report/src/sdlc/single-report-schema.ts
Feature
Show git branch info in the reports
sc-31698
internal loom: https://www.loom.com/share/f3523fbb7d5f4cfabb22134c22a7dfea
=> [Feature] Show git branch information in the comparison reports

piperider_cli/recipes/__init__.py
Bugfix
Fix failed to assign git branch env when using --modified
=> [Bug] Fix failed to assign git branch env when using --modified

piperider_cli/compare_report.py, piperider_cli/dbt/changeset.py, piperider_cli/dbt/utils.py, static_report/src/App.tsx, static_report/src/components/Icons/index.tsx, static_report/src/components/LineageGraph/GraphNode.tsx, static_report/src/components/Overview/ModelList.tsx, static_report/src/components/Widgets/StatDiff.tsx, static_report/src/utils/store.ts
1. Change the row count change color
2. Change the summary stats order (move the impacted column to 2nd)
3. Fix data discrepancy issue for the columns info
4. Fix typo
=> [Feature] slightly adjust the color and column order of comparison summary and report

static_report/src/components/LineageGraph/LineageGraph.tsx
feature
add legend to explain icon's meaning
sc-31797
NONE
=> [Feature] Add status legend to the lineage graph

.github/workflows/e2e-windows-tests.yaml, e2e-jaffle-shop/run.bat, e2e-jaffle-shop/windows-result-checker.py
Run jaffle_shop tests on windows
=> [Chore] Add e2e small set to windows

piperider_cli/recipes/github_action.py
Feature
- GitHub action support `select` and `modified` option
sc-31917
=> [Feature] sc-31917 github action compare support modified and select

piperider_cli/recipes/github_action.py
Hotfix
Cherry-pick #804 
sc-31917
=> [Release] sc-31917 cherry-pick #804

.github/PULL_REQUEST_TITLE_CHECKER.json
Chore
- Update pull request title checker to allow github security Dependabot
N/A
=> [Chore] Update PULL_REQUEST_TITLE_CHECKER.json

piperider_cli/recipes/github_action.py
Hotfix
Cherry-pick #809 
sc-31930
=> [Release] sc-31930 cherry-pick #809

piperider_cli/__init__.py, tests/test_util.py
bug
- jinja filter function may fail if not given the corresponding env var
sc-31885
NONE
=> [Bug] Fix jinja env filter function

static_report/src/components/Common/MasterDetailContainer.tsx, static_report/src/components/Icons/index.tsx, static_report/src/components/LineageGraph/GraphNode.tsx, static_report/src/components/LineageGraph/LineageGraph.tsx, static_report/src/components/LineageGraph/TableSummary.tsx, static_report/src/components/LineageGraph/util.ts, static_report/src/components/MasterSideNav/MasterSideNav.tsx, static_report/src/components/Overview/ChangeSummary.tsx, static_report/src/components/Overview/MetricList.tsx, static_report/src/components/Overview/ModelList.tsx, static_report/src/components/Overview/NodeList.tsx, static_report/src/components/Overview/Overview.tsx, static_report/src/components/SideBar/SideBar.tsx, static_report/src/components/SideBar/SideBarTree.tsx, static_report/src/components/Tables/TableList/TableColumnSchemaList.tsx, static_report/src/components/Tables/TableList/TableListItem.tsx, static_report/src/components/Widgets/ChangeStatusWidget.tsx, static_report/src/pages/CRTableDetailPage.tsx, static_report/src/pages/CRTableListPage.tsx, static_report/src/pages/SRTableDetailPage.tsx, static_report/src/pages/SRTablesListPage.tsx, static_report/src/types/index.ts, static_report/src/utils/__tests__/mergeKeys_test.ts, static_report/src/utils/dbt.ts, static_report/src/utils/mergeKeys.ts, static_report/src/utils/store.ts
In the overview page,
1. Add the impact summary: Potentially Impacted, Assessed, Impacted
2. Add additional column in the overview tables.
Lineage graph
1. Add additional stat: impact
2. Rename the "change status" to "Filter". Use the term "Potentially Impacted"
=> [Feature] Add the impact summary in report

static_report/src/components/SideBar/SideBarTree.tsx
=> [Bug] Don't show folder change icon on model.

piperider_cli/assertion_engine/assertion.py
CI/CD Infra
- Fix flake8 new issue E721
N/A
=> [Chore] Fix flake8 E721 issue

static_report/src/components/Icons/index.tsx, static_report/src/components/LineageGraph/GraphNode.tsx, static_report/src/components/LineageGraph/LineageGraph.tsx, static_report/src/components/Overview/MetricList.tsx, static_report/src/components/Overview/ModelList.tsx, static_report/src/components/Overview/NodeList.tsx, static_report/src/components/SideBar/SideBarTree.tsx, static_report/src/utils/dbt.ts
If a resource is impacted, but not modified, it will be marked as impacted icon
=> [Feature] Add the impacted icon

.github/workflows/dbt-compatible-tests.yaml, setup.py
=> [Chore] Piperider support python >= 3.8

piperider_cli/recipes/__init__.py
Bugfix
- Execute `dbt deps` before `dbt compile`
sc-31991
=> [Bug] sc-31991 Run dbt deps before dbt compile

static_report/src/utils/dbt.ts
bugfix
avoid conflict table name to display wrong data
sc-31952
=> [Bug] Update dbt-node builder

static_report/src/utils/store.ts
The schema change is not in red.
=> [Bug] Show column change in red in the schema compare

piperider_cli/recipes/__init__.py
bug
- when given recipe has `-s` or `--select`, we should replace `<DBT_STATE_PATH>` as well
sc-31885
NONE
=> [Bug] Update select if recipe contains --select option

.github/workflows/dbt-compatible-tests.yaml, tests/test_dbt_manifest_compatible.py
=> [Bug] fix tests broken with dbt 1.4.7

piperider_cli/cli.py, piperider_cli/recipes/__init__.py
bug
- base phase profiling should consider target's listed resources
sc-32019
NONE
=> [Bug] Add dbt list resource to comparing phase env

piperider_cli/dbt/changeset.py, piperider_cli/dbt/list_task.py, piperider_cli/dbtutil.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/utils.py, tests/test_dbt_integeration.py, tests/test_dbt_util.py, tests/test_runner.py
bugfix
In order to make the resources trackable and consistent, we must use the unique_id to refer to the dbt resource
sc-32013
=> [Bug] make dbt resource lister returning unique_id

piperider_cli/cloud/__init__.py, piperider_cli/cloud_connector.py, piperider_cli/githubutil.py, tests/test_github_util.py
Collect the github environment variable from github action context, including PR id, link, title
The command compatible with old piperider cloud.
Feature
=> [Feature] Get the PR information in the github action environment

piperider_cli/dbtutil.py
bug
After `v0.31.0`,  dbt resource were listed in unique id formet
sc-32058
NONE
=> [Bug] Update to use unique id to parse dbt resource

setup.py
Bump snowflake-sqlalchemy version
=> [Chore] Bump snowflake-sqlalchemy version

piperider_cli/compare_report.py, static_report/src/components/Reports/ReportContextBar.tsx
Also add the `.metadata` in the local report.
=> [Feature] Add comparison report metadata in the local report

static_report/src/components/LineageGraph/CopyGraphUrlButton.tsx, static_report/src/components/LineageGraph/LineageGraph.tsx
=> [Chore] keep the lineage state in url

piperider_cli/cli.py, piperider_cli/configuration.py, piperider_cli/dbtutil.py, piperider_cli/initializer.py, piperider_cli/recipe_executor.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/default_recipe_generator.py, piperider_cli/runner.py
feature
- Because we have introduced `--select` option, we would like to change the default behavior of `run` and `compare` to using `--select` instead of `tag`.
sc-31992
NONE
=> [Feature] Change the default behavior of run and compare

piperider_cli/cli.py, piperider_cli/compare_report.py, piperider_cli/dbt/__init__.py, piperider_cli/dbt/list_task.py, piperider_cli/utils.py, piperider_cli/validator.py
chore
make errors or messages more unstandable
sc-32092
-----
* Verify the path existing
* verify content approximately corrent
```
$ piperider compare-reports --base 1.json --target /Users/qrtt1/Downloads/jaffle_shop/.piperider/outputs/dev-20230817114728/run.json
Usage: piperider compare-reports [OPTIONS]
Try 'piperider compare-reports --help' for help.
Error: Invalid value for '--base': missing one of required keys: {'datasource', 'tables', 'dbt'} from: "1.json"
```
=> [Chore] minor fixes to improve messages

setup.py
enhancement
make snowflake connection more stable by upgrading dependencies.
sc-32092
=> [Chore] Update version requirements to snowflake dependencies

piperider_cli/datasource/bigquery.py, setup.py
chore
make sure the user installing new enough library
sc-32092
`python-bigquery-sqlalchemy` has not supported `sqlalchemy 2` yet. 
https://github.com/googleapis/python-bigquery-sqlalchemy/issues/510#issuecomment-1643021766
=> [Chore] Update bigquery denpendencies

piperider_cli/cli.py, piperider_cli/cli_utils/__init__.py, piperider_cli/cli_utils/cloud.py, piperider_cli/cli_utils/compare_with_recipe.py, piperider_cli/cli_utils/run_cmd.py, piperider_cli/configuration.py, piperider_cli/event/__init__.py
enhancement
make piperider cli starting faster
=> [Chore] tuning piperider cli startup speed

piperider_cli/dbt/list_task.py, piperider_cli/runner.py
bugfix
we need the metrics
sc-32169
=> [Bug] Fix upgrade_schema bug to keep metrics data

static_report/src/components/SideBar/SideBar.tsx, static_report/src/utils/dbt.ts
Feature change
1. We have change icon for each item, so we know how to navigate to the changed node
2. We have resource list in the overview page. We can always click the link to open the node.
sc-32148
=> [Feature] Fold all resources in the sidebar by default

piperider_cli/dbt/changeset.py
=> [Feature] Add metric 1.6 to implicit change

piperider_cli/cli.py, piperider_cli/cli_utils/compare_with_recipe.py, piperider_cli/recipe_executor.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/default_recipe_generator.py, piperider_cli/recipes/github_action.py, piperider_cli/runner.py, tests/test_recipe.py
feature
- to support `--skip-datasource` option to piperider compare
sc-32191
NONE
=> [Feature] Support skip-datasource option for piperider compare

piperider_cli/cli_utils/compare_with_recipe.py, piperider_cli/cli_utils/run_cmd.py, piperider_cli/configuration.py, piperider_cli/event/__init__.py, piperider_cli/event/events.py, piperider_cli/event/track.py, piperider_cli/profiler/profiler.py, piperider_cli/recipe_executor.py, piperider_cli/recipes/__init__.py, piperider_cli/recipes/utils.py, piperider_cli/runner.py
In order typ 
Usage event
1. Duration: execution time in seconds
2. Reason: ok | failed | aborted | error
Run event
1. Duration: execution time in seconds
2. Reason: ok | failed | aborted | error
4. Status: true = successful
5. Step
6. Datasource type
Compare event(new)
1. Duration: execution time in seconds
2. Reason: ok | failed | aborted | error
4. Status: true = successful
5. Step
6. Datasource type
=> [Chore] improve telemetry usage and run event

piperider_cli/profiler/schema.json, piperider_cli/runner.py, tests/test_runner.py
* We must upgrade json-schema file to make the report acceptable for cloud
=> [Feature] annotate skip-datasource at run data

piperider_cli/recipes/__init__.py
bug
- we should do dbt parse when skip datasource option is given
sc-32360
NONE
=> [Bug] Do dbt parse when given skip datasource option

setup.py
Bugfix
- Once ruamel.yml releases v0.18, it will fail all of our test cases.
- Before we modify codes, fix the version on v0.17.X to prevent failed issues.
N/A
=> [Chore] Fix ruamel.yaml version on v0.17.*

piperider_cli/cli.py
Document
- Add some comments to explain the feature flag of `--enable-quick-look-share` implemented by #889
sc-32292
=> [Document] Update cli.py to add some comments

piperider_cli/profiler/schema.json
bug
- after `v0.34.0`, `git_branch` information in a run report could be null when compared with git references other than branches.
sc-32458
NONE
=> [Bug] Update report json schema for git branch information

README.md
Readme update
Inform users about the future of PipeRider and recommend migration to Recce
N/A
N/A
=> Updated Readme with Recce info
